package domain.bestiarium.physical_plane.aspirant;

/** Hábitos humanos reconocibles que la deriva somática puede hipertrofiar, nunca pecados/tier de poder. */
public enum AspirantHumanDrive {
    CONSUMPTION,
    COMFORT,
    OPPORTUNISM,
    TERRITORIALITY,
    LOYALTY,
    GROUP_CONFORMITY,
    PURSUIT,
    PREDATION,
    INDEPENDENCE,
    PATIENCE,
    ACCUMULATION,
    ISOLATION,
    DOMINANCE,
    HIERARCHY,
    ROUTINE,
    DISPLAY,
    COMPETITION,
    VIGILANCE,
    PERFORMANCE,
    OBEDIENCE,
    MOBILITY,
    SHELTER_SEEKING,
    AVOIDANCE,
    NOCTURNALITY,
    SOCIAL_BELONGING,
    STIMULATION,
    MEMORY,
    IMITATION,
    CURIOSITY,
    CONCEALMENT,
    EFFICIENCY,
    AMBUSH,
    ADAPTABILITY,
    THERMAL_SEEKING,
    HUMIDITY_SEEKING,
    PARASITISM,
    ATTACHMENT,
    DECAY_ATTRACTION,
    CONTROL,
    WORK_COMPULSION,
    PERSISTENCE,
    MANIPULATION
}
