package domain.ability;

public enum MasteryId {
    PULSION,
    EXPLOSION_CINETICA,
    LIBERACION_HELICOIDAL,
    ANULACION,
    TRANSMUTACION,
    HOMEOSTASIS_TERMICA,
    EMPATIA_ANIMAL,
    INCITAR,
    SANAR,
    REGENERACION_THETA,
    TRAYECTORIA_CONVERGENTE,
    INVISIBILIDAD,
    ESPIRITU_INFATIGABLE,
    TRIBOGENESIS,
    ELECTROGENESIS
}
