package domain.ability;

/** Corpus narrativo-técnico canónico del Grimorio del Maestro. */
final class MasteryNarratives {
    private MasteryNarratives() {}

    static final String PULSION = """
            La mecánica corporal rara vez desperdicia por completo una fuerza ya producida. Tendones, fascias, arcos plantares y cadenas musculares almacenan durante la frenada una fracción de la energía que, si la coordinación lo permite, puede regresar al movimiento siguiente. PULSIÓN estudia ese retorno no como una ayuda accidental, sino como una economía cinética: aprender qué tensiones deben disiparse, cuáles pueden conservarse y en qué instante conviene devolverlas al sistema. Su forma elemental recupera trabajo elástico durante la locomoción; su forma madura reorganiza la transmisión de la cadena cinética para que una acción de máxima carga llegue al impacto con menos pérdidas internas. No aumenta la fuerza disponible. Reduce la cantidad de ella que se pierde antes de alcanzar el mundo.
            """;
    static final String RECICLAJE_DE_PULSION = """
            Toda finta contiene una pequeña contradicción mecánica: el cuerpo acelera para abandonar una trayectoria y, acto seguido, debe pagar otra vez para construir la siguiente. RECICLAJE DE PULSIÓN reduce esa doble factura capturando el retorno elástico de la frenada y devolviéndolo al apoyo posterior. La misma lógica puede emplearse en el salto, donde tobillo, rodilla, cadera y tronco dejan de comportarse como motores independientes y comienzan a transferir una parte mayor de la energía acumulada de un segmento al siguiente. El resultado no procede de generar más trabajo, sino de permitir que una proporción creciente del trabajo ya realizado continúe circulando por la cadena corporal antes de disiparse como calor, oscilación o contracción antagonista.
            """;
    static final String AURA_DE_PULSION = """
            AURA DE PULSIÓN no consiste en rodear el cuerpo con una fuerza externa. El término designa la fase en la que la transmisión elástica deja de ser una corrección local y se convierte en una propiedad global de la cadena cinética. Durante una acción cargada, apoyo, pelvis, tronco, cintura escapular y miembro ejecutor conservan el gradiente de tensión hasta el último instante, evitando liberaciones parciales que normalmente dispersarían la contundencia antes del contacto. El golpe no cuesta menos por ello ni altera cualquier clase de ataque: simplemente llega con una fracción mayor de su impulso todavía organizada en la dirección útil.
            """;

    static final String EXPLOSION_CINETICA = """
            La Energía Maldita no constituye una reserva independiente de la fisiología, ni aparece por simple voluntad. Surge cuando una adversidad imprime sobre la biomáquina una diferencia suficientemente intensa entre el estado que ésta intenta conservar y el estado al que está siendo obligada a alcanzar. Mientras el organismo ordinario disipa esa diferencia mediante fatiga, dolor, temblor, pérdida de coordinación, inflamación o deterioro funcional, el refinamiento comienza cuando esa disipación deja de ser inevitable. La primera disciplina consiste en impedir que la tensión se fragmente: tono muscular, presión interna, actividad autonómica, memoria tisular e impronta conservada en el mucus empiezan a converger sobre un mismo gradiente. La adversidad deja entonces de expresarse únicamente como daño o agotamiento y puede conservarse como diferencia de potencial. Tal potencial no es energía creada de la nada, sino la forma ordenada de una deuda que el organismo habría pagado de manera dispersa. Sólo admite dos resoluciones fundamentales: descargarse o mantenerse. EXPLOSIÓN CINÉTICA pertenece a la primera; ENDURECIMIENTO POTENCIAL, a la segunda.
            """;
    static final String EXPLOSION_CINETICA_VARIANT = """
            Cuando las reservas inmediatamente disponibles se agotan, la biomáquina pierde temporalmente sus vías ordinarias de compensación. En un organismo no refinado, esa pérdida se traduce en descoordinación, descenso de potencia y ruptura progresiva de la ejecución. En uno entrenado para conservar el gradiente ocurre lo contrario: la ausencia de reserva libre impide que la tensión acumulada continúe distribuyéndose de forma parasitaria. El sistema puede resolver de una sola vez aquello que hasta ese instante mantenía repartido entre cadenas musculares, fascia, articulaciones, presión visceral y actividad autonómica. EXPLOSIÓN CINÉTICA no añade potencia externa; concentra pérdidas que normalmente habrían ocurrido por separado y permite que toda la deuda mecánica y energética encuentre una misma dirección de salida. El fenómeno es violento precisamente porque no contiene nada nuevo: contiene demasiado de lo que antes estaba disperso.
            """;
    static final String ENDURECIMIENTO_POTENCIAL = """
            Descargar un gradiente es sencillo en comparación con impedir que se resuelva. ENDURECIMIENTO POTENCIAL conserva la diferencia de potencial sin permitir que encuentre una vía dominante de escape. La tensión deja de concentrarse en un único punto y se distribuye por la arquitectura corporal completa: musculatura, fascia, articulaciones, presión intracavitaria y postura cooperan para sostener una configuración estable. El endurecimiento no corresponde a la piel, al hueso ni a un incremento material de densidad; corresponde al estado del sistema. Un cuerpo relajado absorbe una perturbación deformándose. Un cuerpo organizado bajo potencial propio obliga a esa perturbación a repartirse sobre una estructura que ya se encuentra internamente tensionada. EXPLOSIÓN CINÉTICA enseña a liberar el potencial. ENDURECIMIENTO POTENCIAL enseña a habitarlo.
            """;

    static final String LIBERACION_HELICOIDAL = """
            La locomoción bajo carga depende menos de la fuerza aislada de un músculo que de la continuidad con que pelvis, tronco, cintura escapular y extremidades transmiten fuerzas rotacionales entre apoyos. LIBERACIÓN HELICOIDAL estudia esa continuidad como una arquitectura de restitución: reducir contracciones antagonistas innecesarias, evitar que la torsión útil se pierda entre segmentos y devolver antes al sistema la capacidad de producir trabajo. Su refinamiento no incrementa la carga estructural que el cuerpo puede soportar; estabiliza el régimen de recuperación frente a señales que intentarían interrumpirlo. La sobrecarga absoluta continúa siendo un problema mecánico. Lo que cambia es cuánto tiempo permanece secuestrada la función antes de volver a estar disponible.
            """;
    static final String LIBERACION_HELICOIDAL_VARIANT = """
            La hélice funcional del cuerpo aparece cuando un apoyo no termina donde comienza el siguiente. La rotación de la pelvis prepara el tronco, el tronco ordena la cintura escapular y la tensión residual de una fase se convierte en condición inicial de la posterior. LIBERACIÓN HELICOIDAL reduce el tiempo de restitución precisamente porque deja de tratar cada esfuerzo como un episodio aislado: el sistema recupera antes su capacidad cuando la fuerza que sale de una cadena no obliga a la siguiente a reconstruir desde cero la misma organización postural.
            """;
    static final String OPTIMIZACION_HELICOIDAL = """
            OPTIMIZACIÓN HELICOIDAL representa la fase en la que el organismo aprende a distinguir entre una imposibilidad real de producir trabajo y una señal regulatoria que sólo pretende detener temporalmente la restitución. La técnica no elimina peso, no corrige una sobrecarga estructural y no convierte en móvil a quien ya no puede sostener su propia carga. Su dominio consiste en conservar abierto el proceso de recuperación cuando una interferencia externa intentaría clausurarlo, manteniendo la continuidad del circuito helicoidal sin confundir resistencia a la inhibición con ausencia de límites mecánicos.
            """;

    static final String ANULACION = """
            Muchos objetos poseen dos existencias: una material y otra subjetiva. Un anillo puede ser metal y continuidad afectiva; una prenda, tejido y autoridad; un adorno, materia inerte y la condición que permite a alguien ocupar el espacio con mayor seguridad. ANULACIÓN actúa sobre esa segunda existencia. No destruye el objeto, no modifica su materia y no apaga una capacidad interna del portador. Interrumpe el marco mediante el cual el adversario convierte aquello que lleva en seguridad, estatus, pertenencia, intimidación o confianza. En términos de psicología social, el procedimiento es un frame breaking: introducir una presencia incompatible con la interpretación que el otro estaba sosteniendo hasta que la representación deja de operar con normalidad. El abalorio permanece. El marco que permitía beneficiarse de él, no necesariamente.
            """;
    static final String ANULACION_INCIDENTAL = """
            La forma incidental necesita contacto porque el contacto viola el marco de manera directa. Un objeto íntimo, valioso o identitario conserva parte de su eficacia mientras permanece dentro de un espacio psicológico protegido. Cuando el adversario demuestra que puede alcanzar a su portador y atravesar sin permiso el espacio corporal que debía mantenerlo a salvo, el objeto adquiere una asociación nueva. Ya no representa únicamente aquello que representaba antes: incorpora también la prueba de que alguien exterior pudo entrar. La materia no ha sido contaminada. El significado sí. Mientras el conflicto permanezca abierto, volver al marco anterior exige ignorar una experiencia que acaba de demostrar lo contrario.
            """;
    static final String ANULACION_FUNDACIONAL = """
            La forma fundacional prescinde del contacto porque rompe el marco desde el espacio compartido. Un adversario puede haber construido parte de su presencia alrededor de una joya, una prenda, un peinado, una postura o cualquier otro elemento destinado a producir una lectura concreta de sí mismo. Ese dispositivo sólo funciona plenamente mientras los demás acepten participar en el mismo lenguaje. Una presencia suficientemente estable puede negar esa cooperación: no admira, no teme, no desea, no compite y no valida. El objeto continúa ahí y la apariencia no ha cambiado, pero el portador empieza a percibir que aquello sobre lo que había organizado su performance ya no gobierna la escena. La anulación no vence su imagen; le hace consciente de que estaba actuando.
            """;

    static final String TRANSMUTACION = "La fisiología no mantiene un estado fijo: cicatriza, redistribuye energía, biotransforma tóxicos y reconstruye continuamente la percepción a partir de señales incompletas. TRANSMUTACIÓN reúne técnicas aprendidas para intervenir de forma consciente en esos procesos reguladores. Sus ramas no comparten un supuesto poder genérico: cada una fuerza un mecanismo distinto —reparación fibroproliferativa, financiación metabólica de emergencia, redirección de agresiones químicas o integración perceptiva— y la CLARIVIDENCIA determina hasta qué punto el usuario puede reconocer y gobernar esas transiciones sin confundirlas entre sí.";

    static final String HOMEOSTASIS_TERMICA = """
            La temperatura corporal no depende únicamente de cuánto calor produce el metabolismo, sino de cuánto calor conserva el sistema y de cómo gobierna su superficie de intercambio. Entre piel, ropa, humedad, aire y convección existe una interfaz microclimática inmediata donde se decide qué fracción del calor útil permanece próxima al cuerpo y cuál se pierde hacia el entorno. HOMEOSTASIS TÉRMICA convierte esa interfaz en objeto de regulación consciente: menos fuga, mejor redistribución, control vasomotor más fino y menor necesidad de transformar cada gradiente térmico en una emergencia metabólica. El frío no desaparece. Disminuye la fricción fisiológica que normalmente obliga al organismo a pagar por él.
            """;
    static final String REGULACION_CALORICA_SUPERIOR = """
            Producir recursos y conservarlos no son procesos equivalentes. Una biomáquina puede disponer de agua y sustratos suficientes y, aun así, gastar una fracción innecesaria de ellos corrigiendo oscilaciones térmicas, redistribuyendo perfusión o reconstruyendo un equilibrio que perdió con demasiada facilidad. REGULACIÓN CALÓRICA SUPERIOR reduce esa fragmentación y trata disponibilidad energética, hidratación, circulación periférica e intercambio térmico como partes de un mismo problema de conservación. No consigue que el alimento contenga más ni que el agua adquiera propiedades nuevas; consigue que una parte menor de lo ya disponible desaparezca pagando fricción interna.
            """;
    static final String ADAPTACION_TERMICA = """
            Cuando la conservación basal deja de bastar, el organismo todavía puede modificar activamente el modo en que intercambia calor. Vasoconstricción periférica, redistribución del flujo sanguíneo, termogénesis y control autonómico determinan cuánto puede sacrificarse en la periferia sin comprometer el núcleo funcional. La exposición repetida permite anticipar esas transiciones y ejecutarlas con menos desorganización. ADAPTACIÓN TÉRMICA no elimina la agresión ya acumulada: mantiene un régimen corrector que evita que el gradiente continúe imponiendo nueva deuda mientras la biomáquina conserva recursos suficientes para sostenerlo.
            """;

    static final String EMPATIA_ANIMAL = """
            La comunicación entre especies no comienza con una orden, sino con una clasificación. Antes de acercarse, huir, atacar o cooperar, un animal interpreta orientación corporal, respiración, mirada, olor, ritmo de movimiento, memoria de encuentros y posición relativa dentro del grupo. EMPATÍA ANIMAL sistematiza esa lectura en dos direcciones complementarias. La primera estudia afiliación, confianza y jerarquía hasta volver al usuario socialmente legible para especies dispuestas a establecer vínculo. La segunda estudia la frontera entre presa y cazador: reconocer qué organismo persigue, cuál evita, cuál protege territorio y qué señales anuncian una agresión antes de que ésta se materialice. El trofeo no otorga autoridad por sí mismo; conserva una memoria material de haber comprendido a un depredador desde el único lugar que éste no puede confundir con presa. Por eso la disciplina exige distinguir al cazador sin convertir en víctima a aquello que se acercó confiando.
            """;

    static final String INCITAR = "INCITAR reúne cuatro técnicas de presión interpersonal que explotan regularidades distintas sin atribuirlas a una voluntad sobrenatural. En el varón, PROVOCAR utiliza señales de amenaza y competencia para estrechar la atención del adversario hasta degradar su control fino, mientras GRITO DE GUERRA sincroniza respiración, excitación autonómica y preparación motora para reservar un esfuerzo máximo. En la mujer, CAPITALIZAR convierte el capital erótico —atractivo, presentación, vivacidad y competencia social susceptibles de producir retornos en intercambios— en una ventaja de negociación; RENTABILIZAR añade ahorro social, es decir, el valor económico de una relación previa que reduce fricción, incertidumbre y coste de transacción. Cada manifestación opera únicamente dentro de su contexto y sexo objetivo canónicos.";
    static final String PROVOCAR = "La ira estrecha el campo atencional y favorece respuestas dominadas por saliencia inmediata en detrimento de control ejecutivo, discriminación fina y economía del esfuerzo. PROVOCAR explota deliberadamente señales masculinas de competencia física —postura, ocupación del espacio, mirada y disposición al contacto— para convertir al usuario en el estímulo dominante del encuentro. El adversario no deja de verlo ni de querer alcanzarlo: precisamente por fijarse demasiado en él, pierde precisión de seguimiento y administra peor su reserva de esfuerzo.";
    static final String GRITO_DE_GUERRA = "Una vocalización explosiva previa al esfuerzo puede coordinar espiración forzada, rigidez del tronco, activación simpática y reclutamiento motor. GRITO DE GUERRA comprime esa preparación en una única reserva de acción: no vuelve al usuario más fuerte de manera permanente, sino que alinea el siguiente esfuerzo cuerpo a cuerpo con un estado de PA completamente restituido.";
    static final String CAPITALIZAR = "En economía y sociología del trabajo se han descrito retornos asociados a la apariencia y a otras señales interpersonales cuando el intercambio depende del trato directo. CAPITALIZAR convierte conscientemente ese capital erótico —atractivo, estilo, expresividad y competencia social— en poder de negociación. No altera el valor material del bien: modifica cuánto está dispuesto a ceder un vendedor masculino cuando la compradora posee una ventaja de CARISMA.";
    static final String RENTABILIZAR = "Una relación estable también tiene valor económico porque reduce incertidumbre, vigilancia, negociación repetida y riesgo percibido. RENTABILIZAR explota ese ahorro social acumulado: a la ventaja del capital erótico ya adquirida se suma el rendimiento de la confianza o familiaridad preexistente, de modo que vender deja de ser un encuentro entre desconocidos y pasa a apoyarse en capital relacional ya amortizado.";

    static final String SANAR = """
            La Maldición conserva la memoria de una adversidad y, cuando se libera, tiende a imponer sobre la materia la dirección de aquella ruptura. SANAR estudia la operación inversa: polarizar esa tendencia destructiva hasta convertirla en principio reorganizador. No se trata de acelerar indiscriminadamente una regeneración ni de transferir una sustancia llamada vida. La inversión sólo establece una dirección que otro organismo debe ejecutar con sus propios tejidos, circulación y metabolismo. De ahí su limitación fundamental: el sistema que origina la inversión no puede recibir de sí mismo la distancia causal necesaria para reconstruirse de la misma manera. SANAR comienza, por tanto, donde termina el individuo aislado. Sus formas posteriores exploran qué puede transferirse de un organismo a otro, qué parte de una reserva terminal puede reaprovecharse y hasta qué punto varios sistemas vinculados pueden dejar de regularse como unidades completamente independientes.
            """;
    static final String DRENAR = "Un golpe mortal cuerpo a cuerpo desencadena en la víctima una descarga simpática terminal: la médula suprarrenal libera catecolaminas y el hígado acelera glucogenólisis y gluconeogénesis, elevando la glucosa circulante para sostener una respuesta de emergencia que ya no llegará a consumarse. En paralelo, parte de la adrenalina puede entrar en rutas oxidativas que producen intermediarios quinónicos y alteran el equilibrio redox de ese medio. DRENAR aprovecha esa breve ventana hemática antes de que cesen circulación y gradientes endocrinos. Si PV REGEN seguía operativo, la sangre conserva el sustrato metabólico que la maestría sabe aprovechar. Si PV REGEN estaba inhibido por toxicidad, quemadura u otra agresión sistémica, esa sangre se considera contaminada, pierde su cualidad y hasta su sabor resulta desagradable para el usuario: la fracción metabólica amplificada ya no transfiere fuerza y sólo queda el rendimiento basal ligado a la reserva fisiológica del organismo.";
    static final String RESTAURAR = """
            RESTAURAR no obliga a otro cuerpo a curarse; le devuelve una dirección. Mediante polarización inversa, el usuario transforma temporalmente una corriente asociada a ruptura en un principio de reorganización y la proyecta sobre un organismo distinto. Quien recibe la intervención continúa siendo quien debe reconstruirse: sus tejidos, su circulación, su metabolismo y su propia capacidad regenerativa realizan el trabajo material. El restaurador sólo mantiene durante un tiempo suficiente las condiciones para que el sistema vuelva a reconocer hacia dónde estaba intentando regresar. Por ello existen dos límites independientes: la reserva funcional del usuario determina hasta dónde puede sostener la reorganización, mientras la capacidad regenerativa del receptor determina a qué velocidad puede recorrerla. Uno aporta el principio ordenador; el otro conserva la responsabilidad fisiológica de ejecutarlo.
            """;
    static final String CUSTODIA = """
            La forma culminante de SANAR no consiste en proyectar una fuerza protectora, sino en explotar un fenómeno que sólo aparece cuando la relación entre organismos ya posee historia. Una presencia fiable, amistosa o románticamente significativa puede amortiguar la respuesta de estrés de quien la reconoce como segura, reducir vigilancia defensiva y modificar la regulación neuroendocrina antes de que exista una intervención consciente. CUSTODIA lleva esa amortiguación social a su límite sistémico: dentro de la proximidad de una figura en la que los demás han aprendido a depositar confianza, las biomáquinas dejan de responder como unidades completamente aisladas y sus ritmos regenerativos pueden participar de un mismo balance homeostático. La paradoja doctrinal de FE queda entonces completa. El discípulo pasó tanto tiempo aprendiendo a sostener una convicción propia que su manifestación más alta ya no se mide por cuánto cree en sí mismo, sino por haber llegado a ser una presencia cuya estabilidad permite que otros crean, fisiológicamente, que pueden bajar la guardia. No existe barrera ni fuerza de rechazo; existe una red de regulación compartida entre quienes han concedido al usuario ese lugar.
            """;

    static final String REGENERACION_THETA = """
            La privación prolongada de sueño incrementa la presión homeostática que obliga al sistema nervioso a recuperar estados de baja reactividad. Durante la vigilia forzada aparecen intrusiones de actividad lenta y theta, deterioro del control ejecutivo y una separación progresiva entre la necesidad biológica de dormir y la decisión consciente de permanecer despierto. REGENERACIÓN THETA nace de haber atravesado ese umbral y reconocer después la arquitectura que el organismo intentaba imponer por la fuerza. El usuario aprende a reproducir voluntariamente una postura semiconsciente en la que disminuyen actividad motora, vigilancia y gasto competitivo, permitiendo que la reserva funcional disponible se redirija hacia reparación y restitución. No es sueño instantáneo ni una curación externa: es una suspensión deliberada de prioridades incompatibles con la recuperación, tan frágil que cualquier movimiento, agresión o decisión motora suficiente devuelve de inmediato al organismo a la vigilia operativa.
            """;

    static final String TRAYECTORIA_CONVERGENTE = """
            Una técnica practicada muchas veces no se vuelve únicamente más rápida: ocupa menos espacio dentro de la deliberación. La repetición específica reduce variabilidad, adelanta correcciones y convierte una secuencia de apoyo, rotación, respiración, transferencia e impacto en una sola unidad motora. TRAYECTORIA CONVERGENTE estudia el punto en que la conciencia deja de construir el golpe y se limita a no interferir con una solución que el cuerpo ya conoce. De esa convergencia surge el Flow: no una excitación eufórica, sino una reducción extrema de la distancia entre percibir y ejecutar. Una vez atravesado ese estado, el sistema conserva una referencia interna de lo que significa hacer coincidir todas sus cadenas en un mismo instante. Puede abandonar el Flow, cansarse o equivocarse después; lo que ya no puede perder es la memoria de la diferencia entre golpear y hacer que toda la biomáquina llegue al mismo punto al mismo tiempo.
            """;

    static final String INVISIBILIDAD = """
            La atención no registra todo lo que alcanza la retina. Selecciona amenazas, oportunidades y anomalías; aquello que no exige clasificación urgente se degrada a fondo perceptivo. INVISIBILIDAD no altera la luz ni vuelve transparente el cuerpo. Disciplina postura, mirada, ritmo, trayectoria y economía gestual hasta reducir las señales que fuerzan a otro cerebro a elevar al usuario desde el fondo hasta la figura. Sin embargo, toda identidad proyectada introduce ruido: la ropa comunica pertenencia, los adornos estatus, los objetos función y hasta el intento de ocultarse puede revelar que existe alguien intentando hacerlo. Por eso la disciplina exige desnudez. No como vulnerabilidad, sino como desapego total del yo representado: sin uniforme, rango, propiedad ni última capa cultural que solicite interpretación. Queda un cuerpo que ha aprendido a moverse sin reclamar significado. No desaparece de la materia —puede sonar, oler, sangrar, dejar huellas, tocar y ser tocado—, pero mientras nada obligue a la atención ajena a reclasificarlo, puede ser mirado sin llegar a ser visto.
            """;

    static final String ESPIRITU_INFATIGABLE = """
            La infancia no posee energía infinita; posee otra economía de la fatiga. El organismo prepuberal depende proporcionalmente más del metabolismo oxidativo durante determinadas tareas intermitentes, utiliza menos capacidad glucolítica anaerobia y recupera con rapidez parte de las reservas que el adulto aprende a gastar con mucha mayor potencia. Con el crecimiento aumentan masa, fuerza, capacidad anaerobia y producción instantánea de trabajo, pero también el coste de expresar esas ventajas. A ello se añade una segunda pérdida, ya no estrictamente metabólica: el adulto aprende a interpretar cada señal de cansancio como una orden de cesar. ESPÍRITU INFATIGABLE busca una segunda infancia funcional. No devuelve al cuerpo a un estado infantil, sino que recupera la estrategia de ejecutar locomoción y actividad ordinaria con el mínimo reclutamiento necesario, manteniendo la demanda dentro de un régimen que puede compensarse casi al mismo tiempo que se produce. Cuando aparece una amenaza hostil, esa economía deja de ser prioritaria y la biomáquina vuelve a movilizar reservas con todo su coste. Fuera de ella, el usuario recupera algo que había perdido mucho antes de aprender su nombre: moverse sin convertir cada movimiento en una deuda consciente.
            """;

    static final String TRIBOGENESIS = """
            CONFIGURATIO ORIGINALIS no describe una simple mejora cuantitativa de la biomáquina humana, sino la aparición de una organización material capaz de utilizar intercambios que la fisiología ordinaria sólo tolera como pérdidas. TRIBOGÉNESIS constituye su manifestación térmica. La fricción que normalmente termina dispersándose como calor residual empieza a ser capturada, dirigida y concentrada durante el contacto con estructuras conductoras. Piel, tejido conjuntivo, presión y movimiento dejan de tratar el rozamiento como un subproducto y lo convierten en una interfaz de transferencia. El fenómeno no crea fuego ni presupone combustión espontánea: reorganiza la manera en que deformación y fricción se convierten en gradiente térmico útil. Su importancia no está únicamente en la quemadura resultante, sino en que revela una biomáquina cuya materia empieza a comportarse como si recordara una configuración de vida anterior a los límites ordinarios de su propio sustrato.
            """;
    static final String ELECTROGENESIS = """
            CONFIGURATIO ORIGINALIS encuentra su manifestación complementaria en la electricidad. Toda excitabilidad nerviosa y muscular depende de gradientes iónicos y diferencias de potencial mantenidas a través de membranas; la fisiología ordinaria utiliza esas diferencias localmente y las conserva dentro de márgenes estrechos. ELECTROGÉNESIS aparece cuando la biomáquina deja de confinar por completo esa arquitectura eléctrica a la señalización interna y aprende a sostener una continuidad de potencial hasta la superficie de contacto. No convoca una corriente exterior ni produce electricidad por metáfora: amplía el dominio en el que una diferencia bioeléctrica puede seguir siendo funcional antes de disiparse. El contacto desarmado se convierte así en cierre de circuito. Como en TRIBOGÉNESIS, el verdadero acontecimiento no es el daño que recibe el otro cuerpo, sino que el organismo capaz de producirlo ya no se comporta enteramente conforme a la configuración material que hasta entonces definía sus límites.
            """;
}
