package domain.runic;

import domain.character.CharacterClass;
import java.util.*;

public final class RunicMarkCatalog {
    private static final Map<RunicMarkId, RunicMarkItem> MARKS = build();
    private RunicMarkCatalog() {}
    public static RunicMarkItem require(RunicMarkId id) { RunicMarkItem mark=MARKS.get(id); if(mark==null)throw new IllegalArgumentException("Marca rúnica no catalogada: "+id); return mark; }
    public static List<RunicMarkItem> all() { return List.copyOf(MARKS.values()); }

    private static Map<RunicMarkId, RunicMarkItem> build() {
        EnumMap<RunicMarkId, RunicMarkItem> marks = new EnumMap<>(RunicMarkId.class);
        marks.put(RunicMarkId.PARHELIO, new RunicMarkItem(
                RunicMarkId.PARHELIO,"Parhelio",CharacterClass.INDOMITO,RunicMarkGeometry.PARHELIO_TRIPLE_SOLAR,
                "El Sol no entrega siempre la misma luz, ni la biomáquina responde del mismo modo a cada una de sus horas. PARHELIO registra tres regímenes de una misma trayectoria solar. Bajo el Sol alto, la exposición directa alcanza su expresión más agresiva y el organismo interpreta esa irradiación como una señal de expansión anabólica y reparación; durante la tarde, cuando la luz desciende y se reparte sobre el cuerpo entero, la respuesta deja de buscar el máximo y comienza a conservar lo ganado. Cerca del horizonte, la atmósfera separa durante un instante aquello que durante horas parecía una sola luz: el rayo verde recuerda que una combustión superior no siempre necesita ser mayor, sino más eficiente. Igual que una llama azul aprovecha mejor aquello que consume que una llama anaranjada, la noche transforma la última memoria del día en economía global. La Marca no concede tres dones distintos: geometriza expansión, conservación y eficiencia para que la biomáquina no exija la misma respuesta cuando el cielo ya ha cambiado la pregunta.",
                List.of("DÍA | PV REGEN x3","TARDE | PV REGEN x2,2","NOCHE | Eficiencia global de gasto de PA +25%")));
        marks.put(RunicMarkId.ROSA_DE_LOS_VIENTOS,new RunicMarkItem(
                RunicMarkId.ROSA_DE_LOS_VIENTOS,"Rosa de los Vientos",CharacterClass.MAESTRO,RunicMarkGeometry.ROSA_OCHO_RUMBOS,
                "La Rosa de los Vientos representa una geometría de orientación antes que un mapa. Una ubicación conocida puede fijarse mediante referencias espaciales; una ubicación todavía no cartografiada sólo puede conservarse como relación entre memoria, intención y dirección. La Marca acopla esa representación interna al medio más sensible a diferencias de presión y trayectoria: el aire. El viento guía no porque conozca el destino, sino porque la voluntad del portador proporciona una dirección estable sobre la que una perturbación mínima puede ordenarse. Cuando la posición no existe aún en el mapa, la Memoria del Mundo aporta la referencia que falta.",
                List.of("VIENTO GUÍA [E] | Orienta hacia el objetivo marcado","MEMORIA DEL MUNDO | Si una misión, persona u objeto está registrado pero su ubicación no está cartografiada, el viento revela su dirección","CORDURA | +CLARIVIDENCIA")));
        marks.put(RunicMarkId.RESONANCIA,new RunicMarkItem(
                RunicMarkId.RESONANCIA,"Resonancia",CharacterClass.LUCHADOR,RunicMarkGeometry.RESONANCIA_CONCENTRICA,
                "Todo impacto deja una trayectoria de deformación, transferencia y retorno. La mayor parte se pierde como vibración, calor y desplazamiento; una fracción permanece como memoria estructural de cómo la materia fue obligada a ceder. RESONANCIA reconoce cuándo dos ataques reproducen una geometría suficientemente semejante y hace coincidir la huella del primero con la del segundo. La Maldición no añade un golpe nuevo: impone sobre el impacto presente la memoria material del anterior, de modo que aquello que ya ocurrió vuelve a encontrar una vía para hacerse efectivo.",
                List.of("RESONANCIA | En DESARMADO o melee, reproduce como Energía Maldita el daño físico neto del último ataque primario idéntico")));
        marks.put(RunicMarkId.SILENCIO,new RunicMarkItem(
                RunicMarkId.SILENCIO,"Silencio",CharacterClass.ESPECIALISTA,RunicMarkGeometry.SILENCIO_ANILLO_FONEMICO_ROTO,
                "Una palabra parece indivisible únicamente mientras se pronuncia con suficiente continuidad. Introduce un espacio donde nunca lo hubo, retira una consonante y repite los fragmentos: el oído no se limita a recibir fonemas, intenta reconstruirlos. Allí donde falta una unión fabrica continuidad; allí donde una fricción se repite puede terminar oyendo una consonante que nadie llegó a pronunciar. SILENCIO nace de esa fragilidad. No vence al sonido mediante su ausencia, sino que descompone la cadena que permite atribuirlo correctamente a una fuente. Una pisada, una respiración o el desplazamiento de un cuerpo sólo delatan mientras el oído pueda reunirlos en una misma frase acústica. Fragmentada la continuidad, la percepción completa huecos, desplaza orígenes y construye una presencia distinta de la que realmente los produjo. El cazador perfecto no necesita que el mundo deje de oírlo; le basta con conseguir que, después de oírlo, el mundo haya escuchado otra cosa.",
                List.of("SILENCIO | El portador no emite sonido","FINTAR | El adversario pierde el fijado","DERIVACIÓN FONÉMICA | La protección contundente de la armadura puede filtrar Energía Maldita")));
        marks.put(RunicMarkId.ESPEJO,new RunicMarkItem(
                RunicMarkId.ESPEJO,"Espejo",CharacterClass.INTELECTUAL,RunicMarkGeometry.ESPEJO_ROMBO_BILATERAL,
                "El ser humano nunca ha terminado de aceptar que un reflejo sea solamente luz. Durante siglos cubrió espejos junto a los muertos, temió que una imagen pudiera retener aquello que representaba y sospechó de toda superficie capaz de devolver un cuerpo sin poseerlo. La fotografía heredó la misma inquietud: si una imagen conserva exactamente un instante que ya no existe, resulta difícil no preguntarse qué parte de aquel instante tuvo que quedarse atrás para hacerlo posible. ESPEJO convierte esa sospecha en procedimiento. El reflejo no crea otro individuo ni convoca otro mundo; retiene durante un intervalo mínimo la correspondencia entre una voluntad, un movimiento y el espacio que ambos acaban de atravesar. Cuando el cuerpo abandona esa trayectoria, la imagen todavía conserva una versión coherente de lo sucedido y la Maldición puede tratar esa correspondencia como memoria, obligándola a encontrar nuevamente continuidad en el mismo mundo del que fue extraída. Lo inquietante no es que exista algo al otro lado, sino que este lado pueda recordar dos veces lo mismo.",
                List.of("REFLEJO | En DESARMADO o melee, la secuencia de ataque primario vuelve a ejecutarse con 0,5 s de desfase")));
        marks.put(RunicMarkId.VOTO_VINCULANTE,new RunicMarkItem(
                RunicMarkId.VOTO_VINCULANTE,"Voto Vinculante",CharacterClass.APODERADO,RunicMarkGeometry.VOTO_HEXAGONO_LIGADO,
                "Durante todo el camino de la FE hubo una voz insistiendo en que firmaras. Primero se burló de aquello en lo que empezabas a creer. Después exigió pruebas. Más tarde dejó de discutir y se limitó a esperar, porque toda convicción llevada suficientemente lejos termina encontrándose con una pregunta que ninguna cantidad adicional de fe puede responder: qué estás dispuesto a perder para demostrar que realmente creías en ella. Un Voto Vinculante comienza cuando la respuesta deja de ser hipotética. La voluntad selecciona una posibilidad propia y renuncia deliberadamente a otra que también le pertenecía. Desde ese instante la restricción ya no constituye una carencia impuesta desde fuera: forma parte de la definición que el individuo ha firmado de sí mismo. Cuanto más absoluta sea la renuncia, menor será el número de contradicciones que la voluntad debe sostener simultáneamente y mayor la coherencia con la que puede imponer aquello que permanece. Ningún voto obtiene fuerza de sus palabras; la obtiene de que podría romperse y no se rompe. Llegado este punto quizá comprendas quién llevaba tanto tiempo esperando tu firma. Ya has firmado.",
                List.of("ATAQUES PRIMARIOS | Sólo DESARMADO o melee: añade Energía Maldita bruta igual a FE","RESISTENCIA A FRENESÍ | 0%")));
        marks.put(RunicMarkId.TRANSPOSICION,new RunicMarkItem(
                RunicMarkId.TRANSPOSICION,"Transposición",CharacterClass.HERALDO,RunicMarkGeometry.TRANSPOSICION_CRISOL_CONCENTRICO,
                "Nada concluye cuando deja de cumplir su primer propósito. Toda materia que ha participado en una transformación conserva alguna huella de aquello que fue necesario atravesar para producirla. El mucus constituye el caso más puro: residuo de una adaptación ya consumada, materia aparentemente sobrante que todavía conserva la memoria de la adversidad que obligó a producirla. TRANSPOSICIÓN trata esa memoria como materia prima. No devuelve el residuo a su estado anterior ni fabrica de él una propiedad que nunca poseyó: lo introduce en un nuevo orden y permite que aquello que antes sólo podía existir como recuerdo biológico encuentre otra forma estable desde la que continuar actuando. Lágrima y cristal son destinos diferentes de una misma memoria: una puede transferirse; la otra debe encerrarse en la geometría exacta capaz de conservarla. Allí donde alguien ve solo un residuo desagradable, el portador de la marca rúnica encuentra gozoso una reliquia esperando a ser transpuesta.",
                List.of("TRANSPOSICIÓN | Permite transformar el mucus sobrante en Lágrimas y Cristales de Mucus")));
        return Map.copyOf(marks);
    }
}
