package domain.social;
import domain.character.CharacterClass;
import domain.inventory.item.accessory.OccupationalNarrativeAccessoryCatalog;
import domain.inventory.item.armor.*;
import domain.inventory.item.misc.*;
import domain.inventory.logistics.*;
import java.util.*;
/** patrimonio Feriante por perfil y placement físico. */
public final class FairgroundWorkerStartingEquipmentCatalog {
 private FairgroundWorkerStartingEquipmentCatalog(){}
 public static CanonicalStartingEquipment equipment(Subprofession s,CharacterClass c){
  Objects.requireNonNull(s);Objects.requireNonNull(c);if(s.profession()!=Profession.FAIRGROUND_WORKER)throw new IllegalArgumentException("Sólo Feriante.");
  if(FairgroundWorkerCanonicalProfiles.isDeprecated(s,c))throw new IllegalArgumentException("Perfil Feriante deprecated: "+s+" / "+c);
  boolean m=male(c);CanonicalStartingEquipment b=switch(s){
   case ITINERANT_PUPPETEER_STORYTELLER -> switch(c){
    case INTELECTUAL -> eq(travel(m),List.of("Pan","Cecina","Frutos secos","Uva deshidratada","Odre","Amadou","Pedernal","Caja del Artesano"),90,List.of(ArmorMaterial.PAPER,ArmorMaterial.CLOTH),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT));
    case ESPECIALISTA -> eq(travel(m),List.of("Pan","Fruta","Frutos secos","Odre","Amadou","Pedernal","Caja del Artesano"),78,List.of(ArmorMaterial.CLOTH,ArmorMaterial.CLOTH),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT));
    case HERALDO -> eq(travel(m),List.of("Pan","Bizcocho","Fruta","Odre","Amadou","Pedernal","Caja del Artesano"),105,List.of(ArmorMaterial.PAPER,ArmorMaterial.CLOTH),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT)); default->throw new IllegalArgumentException();};
   case FAIRGROUND_ENTREPRENEUR -> switch(c){
    case INTELECTUAL -> eq(salon(m),List.of("Pan","Bizcocho","Fruta","Odre","Caja de Herramientas","FAROLILLO PORTÁTIL"),135,List.of(ArmorMaterial.PAPER),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT));
    case APODERADO -> eq(salon(m),List.of("Pan","Cecina","Fruta","Odre","Caja de Herramientas","FAROLILLO PORTÁTIL","Apósito de musgo de turbera"),120,List.of(ArmorMaterial.PAPER),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT));
    case HERALDO -> eq(salon(m),List.of("Bizcocho","Fruta","Uva deshidratada","Odre","Caja de Herramientas","FAROLILLO PORTÁTIL"),160,List.of(ArmorMaterial.PAPER),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_HORSE_DRAFT),Optional.of(PersonalTransportType.HORSE_DRAFT)); default->throw new IllegalArgumentException();};
   case TAVERN_MUSICIAN -> switch(c){
    case INTELECTUAL -> eq(tavern(m),List.of("Pan","Fruta","Odre","Amadou","Pedernal","Petaca de hidromiel"),82,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty());
    case ESPECIALISTA -> eq(tavern(m),List.of("Pan","Fruta","Odre","Amadou","Pedernal"),74,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty());
    case HERALDO -> eq(tavern(m),List.of("Bizcocho","Fruta","Odre","Petaca de hidromiel"),96,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty()); default->throw new IllegalArgumentException();};
   case GAME_MASTER -> switch(c){
    case INTELECTUAL -> eq(tavern(m),List.of("Pan","Frutos secos","Odre","Amadou","Pedernal"),100,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty());
    case ESPECIALISTA -> eq(tavern(m),List.of("Pan","Fruta","Odre","Amadou","Pedernal"),86,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty());
    case HERALDO -> eq(tavern(m),List.of("Bizcocho","Frutos secos","Odre","Petaca de hidromiel"),115,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.empty()); default->throw new IllegalArgumentException();};
   case COMPETITION_RIDER -> { if(c!=CharacterClass.INDOMITO)throw new IllegalArgumentException(); yield eq(rider(),List.of("Pan","Frutos secos","Uva deshidratada","Odre","Emplasto de milenrama","Apósito de musgo de turbera"),105,List.of(),List.of(InventoryCompartmentType.BANDOLIER,InventoryCompartmentType.SADDLEBAGS_HORSE_RACING),Optional.of(PersonalTransportType.HORSE_RACING)); }
   case V881_MOTORCYCLE_RACER -> { if(c!=CharacterClass.ESPECIALISTA)throw new IllegalArgumentException(); yield eq(motorcycleRacer(),List.of("Frutos secos","Uva deshidratada","Odre","Caja de Herramientas","Emplasto de milenrama","Apósito de musgo de turbera"),125,List.of(),List.of(InventoryCompartmentType.BACKPACK,InventoryCompartmentType.SADDLEBAGS_MOTORCYCLE_CARDAN),Optional.of(PersonalTransportType.MOTORCYCLE_CARDAN_V881)); }
   case COMPETITION_CYCLIST -> { if(c!=CharacterClass.ESPECIALISTA)throw new IllegalArgumentException(); yield eq(cyclist(),List.of("Frutos secos","Uva deshidratada","Odre","Emplasto de milenrama"),88,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.of(PersonalTransportType.BICYCLE_FOLDING_V881)); }
   case TRIATHLETE -> { if(c!=CharacterClass.INDOMITO)throw new IllegalArgumentException(); yield eq(triathlete(),List.of("Frutos secos","Uva deshidratada","Odre","Emplasto de milenrama","Apósito de musgo de turbera"),92,List.of(),List.of(InventoryCompartmentType.BANDOLIER),Optional.of(PersonalTransportType.BICYCLE_FOLDING_V881)); }
   default->throw new IllegalArgumentException("Feriante fuera de : "+s);};
  var a=OccupationalNarrativeAccessoryCatalog.forProfile(s.name(),c.name());var e=new CanonicalStartingEquipment(b.wornGarments(),b.inventoryObjectNames(),Optional.of(a),b.weaponNames(),b.ammunitionNames(),b.personalTransport(),b.inventoryExpanders(),b.currencyStacks(),b.materialUnits());CanonicalStartingEquipmentPackingPolicy.requireValid(e);return e;
 }
 public static CanonicalLoadoutPlacementPlan placement(Subprofession s,CharacterClass c){return CivilianStartingEquipmentSupport.placement(equipment(s,c));}
 private static boolean male(CharacterClass c){return c==CharacterClass.INTELECTUAL||c==CharacterClass.INDOMITO||c==CharacterClass.LUCHADOR;}
 private static CanonicalStartingEquipment eq(List<ArmorPiece>g,List<String>i,int cash,List<ArmorMaterial>mat,List<InventoryCompartmentType>x,Optional<PersonalTransportType>t){return new CanonicalStartingEquipment(g,i,Optional.empty(),List.of(),List.of(),t,x,List.of(new CurrencyStack(CurrencyType.VALERITA,cash)),mat);}

 private static List<ArmorPiece> rider(){return List.of(ArmorCatalog.innerWorkShirt(),ArmorCatalog.middleRidingWaistcoat(),ArmorCatalog.outerRidingJacketV881(),ArmorCatalog.innerKneeDrawersV881(),ArmorCatalog.middleBreechesV881(),ArmorCatalog.innerFeetHighStockingsV881(),ArmorCatalog.leatherHighRidingBootsV881(),ArmorCatalog.ridingHatV881());}
 private static List<ArmorPiece> motorcycleRacer(){return List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.hardenedLeatherCrossedMotorcycleJacketV881(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.middleBloomersV881(),ArmorCatalog.innerFeetHeavyKnitStockingsV881(),ArmorCatalog.leatherHighRidingBootsV881(),ArmorCatalog.workshopGoggles());}
 private static List<ArmorPiece> cyclist(){return List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.outerNorfolkV881(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.middleBloomersV881(),ArmorCatalog.innerFeetStockingsV881(),ArmorCatalog.outerLeatherAnkleBootsV881(),ArmorCatalog.capV881());}
 private static List<ArmorPiece> triathlete(){return List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerShirt(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.innerKneeDrawersV881(),ArmorCatalog.middleKnickerbockersV881(),ArmorCatalog.innerFeetSocksV881(),ArmorCatalog.outerLeatherAnkleBootsV881(),ArmorCatalog.capV881());}
 private static List<ArmorPiece> travel(boolean m){return m?List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerShirt(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.innerLongDrawersV881(),ArmorCatalog.middleLooseTrousersV881(),ArmorCatalog.innerFeetSocksV881(),ArmorCatalog.outerShortFieldBootsV881(),ArmorCatalog.broadBrimHatV881(),ArmorCatalog.neckerchiefV881()):List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerRegionalBlouse(),ArmorCatalog.middleRegionalBodice(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.innerPetticoatV881(),ArmorCatalog.middleWalkingSkirtV881(),ArmorCatalog.innerFeetStockingsV881(),ArmorCatalog.outerShortFieldBootsV881(),ArmorCatalog.broadBrimHatV881(),ArmorCatalog.neckerchiefV881());}
 private static List<ArmorPiece> salon(boolean m){return m?List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerModularShirtV881(),ArmorCatalog.middleLongWaistcoat(),ArmorCatalog.innerLongDrawersV881(),ArmorCatalog.middleFormalTrousersV881(),ArmorCatalog.innerFeetSocksV881(),ArmorCatalog.leatherOxfordBrogueShoesV881(),ArmorCatalog.outerSackCoatV881(),ArmorCatalog.boaterV881()):List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleRegionalBodice(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.innerPetticoatV881(),ArmorCatalog.middleWalkingSkirtV881(),ArmorCatalog.innerFeetStockingsV881(),ArmorCatalog.outerCourtShoesV881(),ArmorCatalog.outerSackCoatV881(),ArmorCatalog.walkingHatV881());}
 private static List<ArmorPiece> tavern(boolean m){return m?List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerShirt(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.innerLongDrawersV881(),ArmorCatalog.middleStraightTrousersV881(),ArmorCatalog.innerFeetSocksV881(),ArmorCatalog.outerLeatherAnkleBootsV881(),ArmorCatalog.capV881()):List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleWaistcoat(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.innerPetticoatV881(),ArmorCatalog.middleStraightSkirtV881(),ArmorCatalog.innerFeetStockingsV881(),ArmorCatalog.outerLeatherAnkleBootsV881(),ArmorCatalog.capV881());}
}
