package domain.social;
import domain.character.CharacterClass;
import domain.inventory.item.accessory.OccupationalNarrativeAccessoryCatalog;
import domain.inventory.item.armor.*;
import domain.inventory.item.misc.*;
import domain.inventory.logistics.*;
import java.util.*;
/** patrimonio Marinero por perfil; el buque sigue siendo infraestructura laboral, no transporte personal. */
public final class SailorStartingEquipmentCatalog {
 private SailorStartingEquipmentCatalog(){}
 public static CanonicalStartingEquipment equipment(Subprofession s,CharacterClass c){
  if(s.profession()!=Profession.SAILOR)throw new IllegalArgumentException("Sólo Marinero.");if(SailorCanonicalProfiles.isDeprecated(s,c))throw new IllegalArgumentException("Perfil Marinero deprecated: "+s+" / "+c);boolean m=male(c);
  CanonicalStartingEquipment b=switch(s){
   case COASTAL_FISHER -> switch(c){case LUCHADOR->eq(work(m),List.of("Pan","Fruta","Odre","Amadou","Pedernal","Apósito de musgo de turbera","KNIJPKAT","Caja del Artesano"),List.of("Boathook"),List.of(),42,List.of(),List.of(InventoryCompartmentType.BACKPACK));case INDOMITO->eq(work(m),List.of("Pan","Cecina","Frutos secos","Odre","Amadou","Pedernal","Emplasto de milenrama","KNIJPKAT","Caja del Artesano"),List.of("Boathook"),List.of(),36,List.of(),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   case OFFSHORE_FISHER -> switch(c){case INDOMITO->eq(work(m),List.of("Pan","Cecina","Frutos secos","Uva deshidratada","Odre","Apósito de musgo de turbera","Emplasto de milenrama","MAGNETLAMPE","Caja de Herramientas","Inyección estimulante"),List.of("Boathook"),List.of(),58,List.of(),List.of(InventoryCompartmentType.BACKPACK));case APODERADO->eq(work(m),List.of("Pan","Cecina","Frutos secos","Uva deshidratada","Odre","Apósito de musgo de turbera","MAGNETLAMPE","Caja de Herramientas"),List.of("Boathook"),List.of(),64,List.of(),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   case V881_NAVIGATOR -> switch(c){case INTELECTUAL->eq(field(m),List.of("Pan","Bizcocho","Fruta","Odre","MAGNETLAMPE","Astrolabio","Monocular de Reconocimiento V881"),List.of("Boathook"),List.of(),78,List.of(),List.of(InventoryCompartmentType.BACKPACK));case ESPECIALISTA->eq(field(m),List.of("Pan","Bizcocho","Fruta","Odre","MAGNETLAMPE","Astrolabio","Monocular de Reconocimiento V881"),List.of("Boathook"),List.of(),72,List.of(),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   case NAVAL_RAILGUN_GUNNER -> switch(c){case INTELECTUAL->eq(technical(m),List.of("Pan","Cecina","Odre","MAGNETLAMPE","Apósito de musgo de turbera","Emplasto de milenrama","Caja de Herramientas"),List.of("Pistola Autocargadora V881"),List.of("Cargador .45 de Pistola V881"),80,List.of(),List.of(InventoryCompartmentType.BACKPACK));case ESPECIALISTA->eq(technical(m),List.of("Pan","Cecina","Odre","MAGNETLAMPE","Apósito de musgo de turbera","Caja de Herramientas"),List.of("Pistola Autocargadora V881"),List.of("Cargador .45 de Pistola V881"),76,List.of(),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   case NAVAL_ELECTROATMOSPHERIC_NETWORK_ENGINEER -> switch(c){case INTELECTUAL->eq(technical(m),List.of("Pan","Cecina","Odre","MAGNETLAMPE","Apósito de musgo de turbera","Emplasto de milenrama","Caja de Herramientas","Botella de Líquido Refrigerante"),List.of("Martillo de bola"),List.of(),82,List.of(ArmorMaterial.STEEL,ArmorMaterial.VULCANIZED_RUBBER,ArmorMaterial.DIELECTRIC_CLOTH),List.of(InventoryCompartmentType.BACKPACK));case ESPECIALISTA->eq(technical(m),List.of("Pan","Fruta","Odre","MAGNETLAMPE","Apósito de musgo de turbera","Caja de Herramientas","Botella de Líquido Refrigerante"),List.of("Martillo de bola"),List.of(),78,List.of(ArmorMaterial.STEEL,ArmorMaterial.VULCANIZED_RUBBER,ArmorMaterial.DIELECTRIC_CLOTH),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   case MERCHANT_SAILOR -> switch(c){case LUCHADOR->eq(work(m),List.of("Pan","Cecina","Frutos secos","Odre","Amadou","Pedernal","Apósito de musgo de turbera","KNIJPKAT","Caja del Artesano"),List.of("Boathook"),List.of(),58,List.of(),List.of(InventoryCompartmentType.BACKPACK));case INDOMITO->eq(work(m),List.of("Pan","Cecina","Frutos secos","Uva deshidratada","Odre","Amadou","Pedernal","Emplasto de milenrama","KNIJPKAT","Caja del Artesano"),List.of("Boathook"),List.of(),52,List.of(),List.of(InventoryCompartmentType.BACKPACK));case APODERADO->eq(work(m),List.of("Pan","Cecina","Fruta","Odre","Amadou","Pedernal","Apósito de musgo de turbera","KNIJPKAT","Caja del Artesano"),List.of("Boathook"),List.of(),66,List.of(),List.of(InventoryCompartmentType.BACKPACK));default->throw new IllegalArgumentException();};
   default->throw new IllegalArgumentException("Marinero fuera de : "+s);};
  var a=OccupationalNarrativeAccessoryCatalog.forProfile(s.name(),c.name());var e=new CanonicalStartingEquipment(b.wornGarments(),b.inventoryObjectNames(),Optional.of(a),b.weaponNames(),b.ammunitionNames(),Optional.empty(),b.inventoryExpanders(),b.currencyStacks(),b.materialUnits());CanonicalStartingEquipmentPackingPolicy.requireValid(e);return e;
 }
 public static CanonicalLoadoutPlacementPlan placement(Subprofession s,CharacterClass c){return CivilianStartingEquipmentSupport.placement(equipment(s,c));}
 private static boolean male(CharacterClass c){return c==CharacterClass.LUCHADOR||c==CharacterClass.INTELECTUAL||c==CharacterClass.INDOMITO;}
 private static CanonicalStartingEquipment eq(List<ArmorPiece>w,List<String>o,List<String>we,List<String>a,int v,List<ArmorMaterial>mat,List<InventoryCompartmentType>ex){return new CanonicalStartingEquipment(w,o,Optional.empty(),we,a,Optional.empty(),ex,List.of(new CurrencyStack(CurrencyType.VALERITA,v)),mat);}
 private static List<ArmorPiece> work(boolean m){return m?List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerWorkShirt(),ArmorCatalog.middleWorkWaistcoat(),ArmorCatalog.outerWorkSmockV881(),ArmorCatalog.innerKneeDrawersV881(),ArmorCatalog.middleWorkTrousersV881(),ArmorCatalog.innerFeetHeavyWorkSocksV881(),ArmorCatalog.leatherHeavyWorkBootsV881(),ArmorCatalog.workshopBracers(),ArmorCatalog.laborerKerchiefV881()):List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleWorkWaistcoat(),ArmorCatalog.outerWorkSmockV881(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.innerReinforcedPetticoatV881(),ArmorCatalog.middleWorkSkirtV881(),ArmorCatalog.innerFeetHeavyKnitStockingsV881(),ArmorCatalog.leatherHeavyWorkBootsV881(),ArmorCatalog.workshopBracers(),ArmorCatalog.laborerKerchiefV881());}
 private static List<ArmorPiece> field(boolean m){return m?List.of(ArmorCatalog.innerUndershirt(),ArmorCatalog.innerWorkShirt(),ArmorCatalog.middleWorkWaistcoat(),ArmorCatalog.innerLongDrawersV881(),ArmorCatalog.middleWorkTrousersV881(),ArmorCatalog.innerFeetHeavyWorkSocksV881(),ArmorCatalog.leatherHeavyWorkBootsV881(),ArmorCatalog.hardenedLeatherFingerlessGloves(),ArmorCatalog.hunterHatV881()):List.of(ArmorCatalog.innerChemise(),ArmorCatalog.innerBlouse(),ArmorCatalog.middleWorkWaistcoat(),ArmorCatalog.innerWomensDrawersV881(),ArmorCatalog.innerReinforcedPetticoatV881(),ArmorCatalog.middleWorkSkirtV881(),ArmorCatalog.innerFeetHeavyKnitStockingsV881(),ArmorCatalog.leatherHeavyWorkBootsV881(),ArmorCatalog.hardenedLeatherFingerlessGloves(),ArmorCatalog.hunterHatV881());}
 private static List<ArmorPiece> technical(boolean m){var x=new ArrayList<ArmorPiece>(work(m));x.add(ArmorCatalog.workshopGoggles());return List.copyOf(x);}
}
