package domain.inventory.item.accessory;

import domain.inventory.InventoryFootprint;
import domain.inventory.item.AccessoryItem;
import java.util.*;

/** abalorios biográficos de perfiles sociales. Sin explicación mística o técnica añadida. */
public final class OccupationalNarrativeAccessoryCatalog {
    public record PricedAccessory(AccessoryItem item,long priceValeritas){
        public PricedAccessory { Objects.requireNonNull(item); if(priceValeritas<0) throw new IllegalArgumentException("Precio negativo."); }
    }
    private static final Map<String,PricedAccessory> DATA=build();
    private OccupationalNarrativeAccessoryCatalog(){}

    public static AccessoryItem forProfile(String subprofession,String characterClass){
        PricedAccessory p=DATA.get(subprofession+"|"+characterClass);
        if(p==null) throw new IllegalArgumentException("Sin abalorio narrativo : "+subprofession+" / "+characterClass);
        return p.item();
    }
    public static long priceValeritasFor(String subprofession,String characterClass){
        PricedAccessory p=DATA.get(subprofession+"|"+characterClass);
        if(p==null) throw new IllegalArgumentException("Sin precio de abalorio : "+subprofession+" / "+characterClass);
        return p.priceValeritas();
    }
    public static List<AccessoryItem> all(){ return DATA.values().stream().map(PricedAccessory::item).toList(); }
    public static Map<String,PricedAccessory> allPriced(){ return DATA; }

    private static Map<String,PricedAccessory> build(){
        LinkedHashMap<String,PricedAccessory> m=new LinkedHashMap<>();
        put(m,"PRISONER|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Preso / Luchador","Aquí dentro casi todo tiene dueño antes de que llegue a tus manos. Esto era mío antes de la puerta, y por eso me niego a cambiarlo por comida. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"PRISONER|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Preso / Indomito","Aquí dentro casi todo tiene dueño antes de que llegue a tus manos. Esto era mío antes de la puerta, y por eso me niego a cambiarlo por comida. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"PRISONER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Preso / Especialista","Aquí dentro casi todo tiene dueño antes de que llegue a tus manos. Esto era mío antes de la puerta, y por eso me niego a cambiarlo por comida. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"PRISONER|APODERADO",new PricedAccessory(new AccessoryItem("RELICARIO VACÍO — Preso / Apoderado","Aquí dentro casi todo tiene dueño antes de que llegue a tus manos. Esto era mío antes de la puerta, y por eso me niego a cambiarlo por comida. Está vacío porque lo importante no estaba dentro. Lo llevo como recordatorio de algo que decidí sostener aunque nadie pudiera verlo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"UNEMPLOYED|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Desempleado / Intelectual","Cuando dejé de cobrar pensé que vendería esto la primera semana. Sigo llevándolo porque me recuerda que perder un puesto no borró lo que sé hacer. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"UNEMPLOYED|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Desempleado / Especialista","Cuando dejé de cobrar pensé que vendería esto la primera semana. Sigo llevándolo porque me recuerda que perder un puesto no borró lo que sé hacer. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"UNEMPLOYED|HERALDO",new PricedAccessory(new AccessoryItem("COLGANTE GRABADO — Desempleado / Heraldo","Cuando dejé de cobrar pensé que vendería esto la primera semana. Sigo llevándolo porque me recuerda que perder un puesto no borró lo que sé hacer. La gente suele preguntar qué significa el grabado. A veces les digo la verdad y otras veces les cuento la historia que necesito que entiendan.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),35));
        put(m,"WORK_DISABLED|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Incapacitado laboral / Indomito","Antes medía los días por lo que podía terminar. Ahora los mido de otra manera. Lo conservo para no fingir que mi vida empezó el día en que dejé de trabajar. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"WORK_DISABLED|APODERADO",new PricedAccessory(new AccessoryItem("RELICARIO VACÍO — Incapacitado laboral / Apoderado","Antes medía los días por lo que podía terminar. Ahora los mido de otra manera. Lo conservo para no fingir que mi vida empezó el día en que dejé de trabajar. Está vacío porque lo importante no estaba dentro. Lo llevo como recordatorio de algo que decidí sostener aunque nadie pudiera verlo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"INDIGENT|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Indigente / Indomito","He vendido cosas más útiles que ésta. Precisamente por eso sigue conmigo: si vendo también lo último que no sirve para comer, ya no sé qué queda de mí. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"INDIGENT|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Indigente / Especialista","He vendido cosas más útiles que ésta. Precisamente por eso sigue conmigo: si vendo también lo último que no sirve para comer, ya no sé qué queda de mí. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"DISPLACED_RESIDENT|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Habitante desplazado / Intelectual","Lo saqué de casa cuando todavía creíamos que volveríamos en unas semanas. Cada vez pesa menos y, sin embargo, me cuesta más dejarlo. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"DISPLACED_RESIDENT|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Habitante desplazado / Indomito","Lo saqué de casa cuando todavía creíamos que volveríamos en unas semanas. Cada vez pesa menos y, sin embargo, me cuesta más dejarlo. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"DISPLACED_RESIDENT|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Habitante desplazado / Especialista","Lo saqué de casa cuando todavía creíamos que volveríamos en unas semanas. Cada vez pesa menos y, sin embargo, me cuesta más dejarlo. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"DISPLACED_RESIDENT|HERALDO",new PricedAccessory(new AccessoryItem("COLGANTE GRABADO — Habitante desplazado / Heraldo","Lo saqué de casa cuando todavía creíamos que volveríamos en unas semanas. Cada vez pesa menos y, sin embargo, me cuesta más dejarlo. La gente suele preguntar qué significa el grabado. A veces les digo la verdad y otras veces les cuento la historia que necesito que entiendan.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),35));
        put(m,"RECONSTRUCTION_LABORER|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Peón de reconstrucción / Luchador","Lo encontré entre los restos de una casa que ayudé a levantar por segunda vez. Nadie vino a reclamarlo. Yo sí vuelvo cada mañana. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"RECONSTRUCTION_LABORER|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Peón de reconstrucción / Indomito","Lo encontré entre los restos de una casa que ayudé a levantar por segunda vez. Nadie vino a reclamarlo. Yo sí vuelvo cada mañana. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"ELECTROATMOSPHERIC_INFRASTRUCTURE_OPERATOR|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Operario de infraestructura electroatmosférica / Intelectual","Me lo dio el primer encargado que me dejó tocar una conexión sin mirarme por encima del hombro. Todavía compruebo dos veces el aislamiento antes de cerrar. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"ELECTROATMOSPHERIC_INFRASTRUCTURE_OPERATOR|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Operario de infraestructura electroatmosférica / Especialista","Me lo dio el primer encargado que me dejó tocar una conexión sin mirarme por encima del hombro. Todavía compruebo dos veces el aislamiento antes de cerrar. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"STABLE_HAND|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Mozo de cuadras / Indomito","Lo até al primer caballo que dejó de morderme. Cuando murió, el dueño quiso tirarlo. Yo me lo quedé porque fui yo quien aprendió sus manías. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"STABLE_HAND|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Mozo de cuadras / Intelectual","Lo até al primer caballo que dejó de morderme. Cuando murió, el dueño quiso tirarlo. Yo me lo quedé porque fui yo quien aprendió sus manías. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"SANITATION_OPERATOR|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Operario de saneamiento / Indomito","Nadie pregunta quién mantuvo la red cuando el agua corre limpia. Lo llevo para acordarme de las noches en que sí preguntaron porque todo olía mal. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"SANITATION_OPERATOR|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Operario de saneamiento / Especialista","Nadie pregunta quién mantuvo la red cuando el agua corre limpia. Lo llevo para acordarme de las noches en que sí preguntaron porque todo olía mal. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"SANITATION_OPERATOR|APODERADO",new PricedAccessory(new AccessoryItem("RELICARIO VACÍO — Operario de saneamiento / Apoderado","Nadie pregunta quién mantuvo la red cuando el agua corre limpia. Lo llevo para acordarme de las noches en que sí preguntaron porque todo olía mal. Está vacío porque lo importante no estaba dentro. Lo llevo como recordatorio de algo que decidí sostener aunque nadie pudiera verlo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"FARMER|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Agricultor / Luchador","Mi padre decía que la tierra no te debe nada. Lo llevo desde la primera cosecha que salió mal y todavía me enfada que tuviera razón. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"FARMER|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Agricultor / Intelectual","Mi padre decía que la tierra no te debe nada. Lo llevo desde la primera cosecha que salió mal y todavía me enfada que tuviera razón. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"FARMER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Agricultor / Especialista","Mi padre decía que la tierra no te debe nada. Lo llevo desde la primera cosecha que salió mal y todavía me enfada que tuviera razón. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"FARMER|APODERADO",new PricedAccessory(new AccessoryItem("RELICARIO VACÍO — Agricultor / Apoderado","Mi padre decía que la tierra no te debe nada. Lo llevo desde la primera cosecha que salió mal y todavía me enfada que tuviera razón. Está vacío porque lo importante no estaba dentro. Lo llevo como recordatorio de algo que decidí sostener aunque nadie pudiera verlo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"LIVESTOCK_KEEPER|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Ganadero / Indomito","Tiene marcas de dientes de un animal que juré que no volvería a acercarse a mí. Al día siguiente fui yo quien abrió el cercado. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"LIVESTOCK_KEEPER|INTELECTUAL",new PricedAccessory(new AccessoryItem("CERA DE UN INTELECTUAL — Ganadero / Intelectual","Tiene marcas de dientes de un animal que juré que no volvería a acercarse a mí. Al día siguiente fui yo quien abrió el cercado. No sé si la historia que me contaron sobre su antiguo dueño era cierta. Lo que sí sé es lo que aprendí mientras intentaba averiguarlo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"HORTICULTURIST|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Horticultora de precisión / Especialista","Lo uso para recordar qué variedad salvé de una temporada de humedad. Parece una tontería hasta que una planta paga tres meses de trabajo. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"FOREST_LUMBERJACK|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Leñador forestal / Luchador","Lo tallé durante una parada porque estaba demasiado cansado para hablar. Tiene una muesca por cada invierno que he vuelto entero. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"FOREST_LUMBERJACK|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Leñador forestal / Indomito","Lo tallé durante una parada porque estaba demasiado cansado para hablar. Tiene una muesca por cada invierno que he vuelto entero. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"EXTRACTION_MINER|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Minero de extracción / Indomito","Salió conmigo de una galería que no volvió a abrirse. No creo que proteja de nada; simplemente sé quién no salió con nosotros. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"STEVEDORE|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Estibador / Luchador","Lo recogí de una caja rota cuyo contenido valía más que mi cuadrilla entera. El capataz dijo que la basura no figuraba en el manifiesto. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"AGRICULTURAL_SELECTOR_CONDITIONER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESPEJO DE BOLSILLO — Seleccionadora y acondicionadora agrícola / Especialista","Lo guardé de un lote perfecto que nadie vio porque mi trabajo consiste precisamente en que nada defectuoso llegue al comprador. Lo miro para comprobar una cosa concreta, no para buscar presagios; me recuerda que la precisión empieza por no engañarse sobre lo que uno tiene delante. La precisión empieza por no engañarse sobre lo que uno tiene delante.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"HAULAGE_LABORER|LUCHADOR",new PricedAccessory(new AccessoryItem("ANILLO DE PROMESA — Peón de acarreo / Luchador","Lo llevo colgado del arnés desde que una carga mal repartida tumbó un carro y casi aplasta a dos hombres. Ahora reparto el peso antes de escuchar las prisas. No necesito que me dé suerte; necesito recordar por qué sigo levantando peso cuando los demás ya han parado.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"HAULAGE_LABORER|INDOMITO",new PricedAccessory(new AccessoryItem("AMULETO DE COBRE — Peón de acarreo / Indomito","Lo llevo colgado del arnés desde que una carga mal repartida tumbó un carro y casi aplasta a dos hombres. Ahora reparto el peso antes de escuchar las prisas. Nunca he creído que el cobre me proteja. Me basta con que haya sobrevivido conmigo a días que yo tampoco pensaba aguantar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"BARBER|INTELECTUAL",new PricedAccessory(new AccessoryItem("NAVAJA MELLADA DE APRENDIZ — Barber / Intelectual","Mi maestro me la retiró cuando por fin aprendí a afilar sin arrancar metal de más. La guardo porque todavía puedo señalar cada error que cometí en ese filo.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"BARBER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("PEINE DE DIENTES REPARADOS — Barber / Especialista","Lo reparé tantas veces que ya no sé qué diente era original. Me sirve para recordar que una mano precisa también se reconoce por lo que decide no tirar.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"SALON_HAIRDRESSER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("HORQUILLA DE PLATA DOBLADA — Salon Hairdresser / Especialista","La clienta dijo que estaba arruinada; yo tardé una tarde en devolverle la forma. Me la regaló después y desde entonces la llevo como medida de lo que considero un acabado aceptable.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),34));
        put(m,"SALON_HAIRDRESSER|HERALDO",new PricedAccessory(new AccessoryItem("TARJETA DE CITA PERFUMADA — Salon Hairdresser / Heraldo","Mi primer cliente importante canceló tres veces y volvió la cuarta con otras dos personas. Conservo la tarjeta porque desde aquel día entendí que un salón vive tanto de memoria como de tijeras.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),12));
        put(m,"HIDE_PREPARER|LUCHADOR",new PricedAccessory(new AccessoryItem("GANCHO DE COBRE DESGASTADO — Hide Preparer / Luchador","Mi padre lo usaba para arrastrar pieles antes de que yo pudiera levantarlas. Ya no lo empleo en el trabajo; lo llevo para no olvidar de dónde salió la fuerza que ahora todos dan por sentada.",0.060,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),11));
        put(m,"HIDE_PREPARER|INDOMITO",new PricedAccessory(new AccessoryItem("FICHA DE TURNO MANCHADA — Hide Preparer / Indomito","Me dieron esta ficha en una semana en la que tres hombres abandonaron por el olor. Yo terminé el turno y el siguiente. No demuestra nada salvo que estuve allí.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),7));
        put(m,"INDUSTRIAL_TANNER|INTELECTUAL",new PricedAccessory(new AccessoryItem("MUESTRA DE CUERO FALLIDA — Industrial Tanner / Intelectual","Mi mejor lección fue este trozo arruinado. Lo corté de un lote que creí entender demasiado pronto; desde entonces prefiero comprobar una causa antes de presumir que la conozco.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"INDUSTRIAL_TANNER|APODERADO",new PricedAccessory(new AccessoryItem("CORDÓN DE LOTE NUMERADO — Industrial Tanner / Apoderado","Lo até al primer lote que llevé de principio a fin sin que nadie corrigiera mis tiempos. No tiene valor fuera del taller, pero para mí marca el día en que dejaron de vigilarme.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),9));
        put(m,"LEATHER_FINISHER_GRADER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("TIRA DE CUERO DE DESCARTE — Leather Finisher Grader / Especialista","La rechazaron por una marca que casi nadie veía. La guardé porque yo sí la vi, y porque mi trabajo empieza exactamente donde otros dicen que ya está bien.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),10));
        put(m,"WORK_TAILOR|INTELECTUAL",new PricedAccessory(new AccessoryItem("PATRÓN PLEGADO DE CHAQUETA — Work Tailor / Intelectual","Mi primer patrón útil está lleno de correcciones en los márgenes. Lo guardo porque cada línea tachada explica mejor mi oficio que una prenda terminada.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),13));
        put(m,"WORK_TAILOR|APODERADO",new PricedAccessory(new AccessoryItem("DEDALES GEMELOS DESPAREJADOS — Work Tailor / Apoderado","Perdí uno durante una temporada de encargos que parecía no terminar nunca. Compré otro distinto y seguí. Los llevo juntos porque el trabajo rara vez espera a que todo vuelva a estar completo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),15));
        put(m,"PRECISION_PATTERNMAKER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("REGLA CORTA MARCADA — Precision Patternmaker / Especialista","La corté para que cupiera en mi caja y después lamenté haberlo hecho. Ahora conozco cada marca de memoria; si una medida no encaja, el error es mío y no de la regla.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),17));
        put(m,"SALON_DRESSMAKER|HERALDO",new PricedAccessory(new AccessoryItem("BOTÓN DE UN VESTIDO RECHAZADO — Salon Dressmaker / Heraldo","La clienta rechazó el vestido y conservó sólo el botón para enseñarme qué esperaba de mí. Yo conservé otro. Desde entonces escucho mejor antes de cortar.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"STONE_SETTER|LUCHADOR",new PricedAccessory(new AccessoryItem("CUÑA PARTIDA DE OBRA — Stone Setter / Luchador","La partí intentando corregir una piedra que pesaba más que mi paciencia. La guardo porque aquel día aprendí que empujar más fuerte no arregla una mala colocación.",0.100,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"STONE_SETTER|INDOMITO",new PricedAccessory(new AccessoryItem("CORDÓN DE PLOMADA ANUDADO — Stone Setter / Indomito","Este cordón sobrevivió a una obra en la que cambiaron tres cuadrillas y dos capataces. Yo seguí allí hasta cerrar el último tramo. Los nudos son míos.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),9));
        put(m,"STONEWORK_MASTER|INTELECTUAL",new PricedAccessory(new AccessoryItem("TROZO DE TRAZADO ENCERADO — Stonework Master / Intelectual","Lo recorté de un plano de obra que obligué a rehacer antes de colocar una sola piedra. Me costó una discusión y ahorró semanas de correcciones.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"PRECISION_STONECUTTER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("GALGA DE LATÓN RAYADA — Precision Stonecutter / Especialista","Las rayas son de piezas que no acepté. La llevo porque una tolerancia no mejora por cansancio ni por prisa.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),21));
        put(m,"STRUCTURAL_CARPENTER|LUCHADOR",new PricedAccessory(new AccessoryItem("CLAVIJA DE ROBLE ASTILLADA — Structural Carpenter / Luchador","La saqué de un entramado que cedió antes de que termináramos de cargarlo. Desde entonces pruebo cada unión antes de confiar mi peso a ella.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),9));
        put(m,"STRUCTURAL_CARPENTER|INDOMITO",new PricedAccessory(new AccessoryItem("TIRANTE DE CUERO RECOSIDO — Structural Carpenter / Indomito","Lo cosí durante una noche de lluvia para poder seguir trabajando al amanecer. Todavía aguanta, aunque ya no lo necesito.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),12));
        put(m,"BENCH_CARPENTER|INTELECTUAL",new PricedAccessory(new AccessoryItem("ENSAMBLE DE PRUEBA — Bench Carpenter / Intelectual","Es una unión que no pertenece a ningún mueble. La hice para entender por qué otra fallaba; desde entonces la guardo cuando necesito pensar con las manos.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"BENCH_CARPENTER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("VIRUTA ENROLLADA EN RESINA — Bench Carpenter / Especialista","Salió de una pasada limpia que no tuve que repetir. La conservé por vanidad, y no me molesta admitirlo.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),8));
        put(m,"CABINETMAKER|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLANTILLA DE CAJÓN — Cabinetmaker / Intelectual","La guardo porque la hice para un encargo demasiado complejo para confiar en la memoria. Después fabriqué cinco piezas iguales sin volver a medir el original.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),19));
        put(m,"CABINETMAKER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("MUESTRA DE CHAPA PULIDA — Cabinetmaker / Especialista","Es demasiado pequeña para venderla y demasiado buena para tirarla. La llevo porque me recuerda cuánto puede cambiar una superficie después de una hora más de trabajo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),20));
        put(m,"CABINETMAKER|HERALDO",new PricedAccessory(new AccessoryItem("TIRADOR DE MUEBLE DEVUELTO — Cabinetmaker / Heraldo","Un cliente pagó por sustituirlo porque decía que parecía barato. Yo lo guardé porque otra persona lo habría considerado hermoso. El gusto también tiene dueño.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"ITINERANT_PUPPETEER_STORYTELLER|INTELECTUAL",new PricedAccessory(new AccessoryItem("TÍTERE DE REPERTORIO — Itinerant Puppeteer Storyteller / Intelectual","Lo llevo conmigo desde una gira en la que una plaza entera terminó repitiendo una frase que improvisé para salir de un silencio. Cada reparación conserva una ciudad distinta. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.180,new InventoryFootprint(2,1),List.of(),List.of(),List.of()),35));
        put(m,"ITINERANT_PUPPETEER_STORYTELLER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("TÍTERE DE REPERTORIO — Itinerant Puppeteer Storyteller / Especialista","Lo llevo conmigo desde una gira en la que una plaza entera terminó repitiendo una frase que improvisé para salir de un silencio. Cada reparación conserva una ciudad distinta. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.180,new InventoryFootprint(2,1),List.of(),List.of(),List.of()),35));
        put(m,"ITINERANT_PUPPETEER_STORYTELLER|HERALDO",new PricedAccessory(new AccessoryItem("TÍTERE DE REPERTORIO — Itinerant Puppeteer Storyteller / Heraldo","Lo llevo conmigo desde una gira en la que una plaza entera terminó repitiendo una frase que improvisé para salir de un silencio. Cada reparación conserva una ciudad distinta. La gente pregunta por él y la respuesta suele decirme tanto del interlocutor como lo que yo cuento.",0.180,new InventoryFootprint(2,1),List.of(),List.of(),List.of()),35));
        put(m,"FAIRGROUND_ENTREPRENEUR|INTELECTUAL",new PricedAccessory(new AccessoryItem("FICHA DE FERIA CANCELADA — Fairground Entrepreneur / Intelectual","La guardé de una feria que perdí por lluvia después de pagar terreno, comida y jornales. Desde entonces cuento primero cuánto puedo perder y sólo después cuánto espero ganar. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"FAIRGROUND_ENTREPRENEUR|APODERADO",new PricedAccessory(new AccessoryItem("FICHA DE FERIA CANCELADA — Fairground Entrepreneur / Apoderado","La guardé de una feria que perdí por lluvia después de pagar terreno, comida y jornales. Desde entonces cuento primero cuánto puedo perder y sólo después cuánto espero ganar. Lo llevo porque mantener una responsabilidad durante días importa más que resolverla una sola vez.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"FAIRGROUND_ENTREPRENEUR|HERALDO",new PricedAccessory(new AccessoryItem("FICHA DE FERIA CANCELADA — Fairground Entrepreneur / Heraldo","La guardé de una feria que perdí por lluvia después de pagar terreno, comida y jornales. Desde entonces cuento primero cuánto puedo perder y sólo después cuánto espero ganar. La gente pregunta por él y la respuesta suele decirme tanto del interlocutor como lo que yo cuento.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"TAVERN_MUSICIAN|INTELECTUAL",new PricedAccessory(new AccessoryItem("INSTRUMENTO DE TABERNA — Tavern Musician / Intelectual","Es el instrumento con el que trabajo cada noche. Tiene marcas de mesas, viajes y reparaciones; sé qué pieza vibra antes de que el público note que algo está mal. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",1.200,new InventoryFootprint(3,2),List.of(),List.of(),List.of()),90));
        put(m,"TAVERN_MUSICIAN|ESPECIALISTA",new PricedAccessory(new AccessoryItem("INSTRUMENTO DE TABERNA — Tavern Musician / Especialista","Es el instrumento con el que trabajo cada noche. Tiene marcas de mesas, viajes y reparaciones; sé qué pieza vibra antes de que el público note que algo está mal. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",1.200,new InventoryFootprint(3,2),List.of(),List.of(),List.of()),90));
        put(m,"TAVERN_MUSICIAN|HERALDO",new PricedAccessory(new AccessoryItem("INSTRUMENTO DE TABERNA — Tavern Musician / Heraldo","Es el instrumento con el que trabajo cada noche. Tiene marcas de mesas, viajes y reparaciones; sé qué pieza vibra antes de que el público note que algo está mal. La gente pregunta por él y la respuesta suele decirme tanto del interlocutor como lo que yo cuento.",1.200,new InventoryFootprint(3,2),List.of(),List.of(),List.of()),90));
        put(m,"GAME_MASTER|INTELECTUAL",new PricedAccessory(new AccessoryItem("JUEGO DE FICHAS DESGASTADAS — Game Master / Intelectual","Estas fichas han pasado por mesas donde una regla mal explicada habría acabado en pelea. Las cuento antes y después de cada partida porque arbitrar empieza mucho antes de decidir quién ganó. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.120,new InventoryFootprint(1,2),List.of(),List.of(),List.of()),28));
        put(m,"GAME_MASTER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("JUEGO DE FICHAS DESGASTADAS — Game Master / Especialista","Estas fichas han pasado por mesas donde una regla mal explicada habría acabado en pelea. Las cuento antes y después de cada partida porque arbitrar empieza mucho antes de decidir quién ganó. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.120,new InventoryFootprint(1,2),List.of(),List.of(),List.of()),28));
        put(m,"GAME_MASTER|HERALDO",new PricedAccessory(new AccessoryItem("JUEGO DE FICHAS DESGASTADAS — Game Master / Heraldo","Estas fichas han pasado por mesas donde una regla mal explicada habría acabado en pelea. Las cuento antes y después de cada partida porque arbitrar empieza mucho antes de decidir quién ganó. La gente pregunta por él y la respuesta suele decirme tanto del interlocutor como lo que yo cuento.",0.120,new InventoryFootprint(1,2),List.of(),List.of(),List.of()),28));
        put(m,"ROAD_GUIDE|INTELECTUAL",new PricedAccessory(new AccessoryItem("CINTA DE CAMINO ANUDADA — Road Guide / Intelectual","La até a una rama para marcar un desvío durante una crecida. Volví meses después y seguía allí; desde entonces la llevo para recordar que un camino sólo existe mientras alguien puede atravesarlo. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"ROAD_GUIDE|INDOMITO",new PricedAccessory(new AccessoryItem("CINTA DE CAMINO ANUDADA — Road Guide / Indomito","La até a una rama para marcar un desvío durante una crecida. Volví meses después y seguía allí; desde entonces la llevo para recordar que un camino sólo existe mientras alguien puede atravesarlo. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"ROAD_GUIDE|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CINTA DE CAMINO ANUDADA — Road Guide / Especialista","La até a una rama para marcar un desvío durante una crecida. Volví meses después y seguía allí; desde entonces la llevo para recordar que un camino sólo existe mientras alguien puede atravesarlo. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"WILDLIFE_TRACKER|INDOMITO",new PricedAccessory(new AccessoryItem("MOLDE DE HUELLA EN CERA — Wildlife Tracker / Indomito","Lo tomé de una huella que casi descarté por vieja. Me llevó hasta un dormidero activo dos kilómetros después. Lo guardo porque el terreno habla incluso cuando parece repetirse. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),19));
        put(m,"WILDLIFE_TRACKER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("MOLDE DE HUELLA EN CERA — Wildlife Tracker / Especialista","Lo tomé de una huella que casi descarté por vieja. Me llevó hasta un dormidero activo dos kilómetros después. Lo guardo porque el terreno habla incluso cuando parece repetirse. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),19));
        put(m,"PROFESSIONAL_HUNTER|LUCHADOR",new PricedAccessory(new AccessoryItem("CORREA DE PRESA REPARADA — Professional Hunter / Luchador","Se rompió cuando todavía faltaban horas para regresar. La reparé allí mismo y terminé el encargo. No la uso ya, pero me recuerda que cobrar depende también de traer de vuelta lo conseguido. Mi jornada me ha enseñado a no confundir fuerza con prisa.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),17));
        put(m,"PROFESSIONAL_HUNTER|INDOMITO",new PricedAccessory(new AccessoryItem("CORREA DE PRESA REPARADA — Professional Hunter / Indomito","Se rompió cuando todavía faltaban horas para regresar. La reparé allí mismo y terminé el encargo. No la uso ya, pero me recuerda que cobrar depende también de traer de vuelta lo conseguido. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),17));
        put(m,"PROFESSIONAL_HUNTER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CORREA DE PRESA REPARADA — Professional Hunter / Especialista","Se rompió cuando todavía faltaban horas para regresar. La reparé allí mismo y terminé el encargo. No la uso ya, pero me recuerda que cobrar depende también de traer de vuelta lo conseguido. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),17));
        put(m,"TRAPPER|INTELECTUAL",new PricedAccessory(new AccessoryItem("GATILLO DE TRAMPA DESACTIVADO — Trapper / Intelectual","Pertenece a una trampa que falló tres noches seguidas. La desmonté hasta entender por qué. La pieza no sirve ya para capturar nada; a mí me sirve para no culpar al animal de mis errores. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"TRAPPER|INDOMITO",new PricedAccessory(new AccessoryItem("GATILLO DE TRAMPA DESACTIVADO — Trapper / Indomito","Pertenece a una trampa que falló tres noches seguidas. La desmonté hasta entender por qué. La pieza no sirve ya para capturar nada; a mí me sirve para no culpar al animal de mis errores. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"TRAPPER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("GATILLO DE TRAMPA DESACTIVADO — Trapper / Especialista","Pertenece a una trampa que falló tres noches seguidas. La desmonté hasta entender por qué. La pieza no sirve ya para capturar nada; a mí me sirve para no culpar al animal de mis errores. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.090,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"COASTAL_FISHER|LUCHADOR",new PricedAccessory(new AccessoryItem("FLOTADOR DE RED REPARADO — Coastal Fisher / Luchador","Lo reparé tantas veces que ya pesa distinto de los demás. Lo guardo porque una jornada cerca de costa también se pierde si una pieza pequeña falla en el momento equivocado. Mi jornada me ha enseñado a no confundir fuerza con prisa.",0.100,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),12));
        put(m,"COASTAL_FISHER|INDOMITO",new PricedAccessory(new AccessoryItem("FLOTADOR DE RED REPARADO — Coastal Fisher / Indomito","Lo reparé tantas veces que ya pesa distinto de los demás. Lo guardo porque una jornada cerca de costa también se pierde si una pieza pequeña falla en el momento equivocado. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.100,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),12));
        put(m,"OFFSHORE_FISHER|INDOMITO",new PricedAccessory(new AccessoryItem("TROZO DE CABO SALINIZADO — Offshore Fisher / Indomito","Lo corté después de una noche en la que no pudimos volver a puerto. La sal lo dejó rígido. Cuando lo toco recuerdo que lejos de costa ninguna avería espera a que uno esté descansado. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.120,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),15));
        put(m,"OFFSHORE_FISHER|APODERADO",new PricedAccessory(new AccessoryItem("TROZO DE CABO SALINIZADO — Offshore Fisher / Apoderado","Lo corté después de una noche en la que no pudimos volver a puerto. La sal lo dejó rígido. Cuando lo toco recuerdo que lejos de costa ninguna avería espera a que uno esté descansado. Lo llevo porque mantener una responsabilidad durante días importa más que resolverla una sola vez.",0.120,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),15));
        put(m,"V881_NAVIGATOR|INTELECTUAL",new PricedAccessory(new AccessoryItem("REGLA DE RUMBO MARCADA — V881 Navigator / Intelectual","Tiene una marca del día en que corregí el rumbo antes de que el cambio de viento apareciera en los instrumentos. No fue intuición: llevaba horas mirando cómo respondía el mar. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.060,new InventoryFootprint(1,2),List.of(),List.of(),List.of()),32));
        put(m,"V881_NAVIGATOR|ESPECIALISTA",new PricedAccessory(new AccessoryItem("REGLA DE RUMBO MARCADA — V881 Navigator / Especialista","Tiene una marca del día en que corregí el rumbo antes de que el cambio de viento apareciera en los instrumentos. No fue intuición: llevaba horas mirando cómo respondía el mar. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.060,new InventoryFootprint(1,2),List.of(),List.of(),List.of()),32));
        put(m,"NAVAL_RAILGUN_GUNNER|INTELECTUAL",new PricedAccessory(new AccessoryItem("FICHA DE DISPARO ANULADO — Naval Railgun Gunner / Intelectual","La orden llegó y la anulamos antes de liberar energía porque el sector dejó de estar limpio. La guardo porque mi oficio también se mide por los disparos que no hacemos. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"NAVAL_RAILGUN_GUNNER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("FICHA DE DISPARO ANULADO — Naval Railgun Gunner / Especialista","La orden llegó y la anulamos antes de liberar energía porque el sector dejó de estar limpio. La guardo porque mi oficio también se mide por los disparos que no hacemos. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"NAVAL_ELECTROATMOSPHERIC_NETWORK_ENGINEER|INTELECTUAL",new PricedAccessory(new AccessoryItem("AISLANTE QUEMADO DE DIAGNÓSTICO — Naval Electroatmospheric Engineer / Intelectual","Lo saqué de una derivación que parecía sana hasta que medí el circuito por secciones. La avería era pequeña; el buque no. Desde entonces empiezo por lo que puedo demostrar. Lo guardo porque entender por qué ocurrió me ha servido más veces que recordar solamente que ocurrió.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),20));
        put(m,"NAVAL_ELECTROATMOSPHERIC_NETWORK_ENGINEER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("AISLANTE QUEMADO DE DIAGNÓSTICO — Naval Electroatmospheric Engineer / Especialista","Lo saqué de una derivación que parecía sana hasta que medí el circuito por secciones. La avería era pequeña; el buque no. Desde entonces empiezo por lo que puedo demostrar. Lo guardo porque mis manos recuerdan detalles que una explicación suele omitir.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),20));
        put(m,"MERCHANT_SAILOR|LUCHADOR",new PricedAccessory(new AccessoryItem("PRECINTO DE CARGA ABIERTO — Merchant Sailor / Luchador","Lo guardé de una caja que cruzó tres puertos sin perderse. Mi nombre no figuraba en la mercancía, pero sí en la guardia que evitó que terminara en otra bodega. Mi jornada me ha enseñado a no confundir fuerza con prisa.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),13));
        put(m,"MERCHANT_SAILOR|INDOMITO",new PricedAccessory(new AccessoryItem("PRECINTO DE CARGA ABIERTO — Merchant Sailor / Indomito","Lo guardé de una caja que cruzó tres puertos sin perderse. Mi nombre no figuraba en la mercancía, pero sí en la guardia que evitó que terminara en otra bodega. Lo llevo en jornadas en las que seguir funcionando es ya parte del trabajo.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),13));
        put(m,"MERCHANT_SAILOR|APODERADO",new PricedAccessory(new AccessoryItem("PRECINTO DE CARGA ABIERTO — Merchant Sailor / Apoderado","Lo guardé de una caja que cruzó tres puertos sin perderse. Mi nombre no figuraba en la mercancía, pero sí en la guardia que evitó que terminara en otra bodega. Lo llevo porque mantener una responsabilidad durante días importa más que resolverla una sola vez.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),13));
        //  — perfiles nuevos de Cortesana y Herrero.
        put(m,"SEX_WORKER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CINTA DE LA PRIMERA HABITACIÓN — Sex Worker / Especialista","La guardé cuando todavía pensaba que sólo iba a trabajar allí unos días. Después aprendí que una habitación puede convertirse en un lugar seguro o en una jaula dependiendo de quién tenga la llave. Yo sigo teniendo la mía.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"SALON_COURTESAN|HERALDO",new PricedAccessory(new AccessoryItem("GUANTE DE UNA RECEPCIÓN — Salon Courtesan / Heraldo","Lo guardo porque después de una noche tuve que cambiar tres veces de mesa sin que nadie notara que lo estaba haciendo. El guante acabó manchado. La conversación, no.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),38));
        put(m,"PROFESSIONAL_COMPANION|APODERADO",new PricedAccessory(new AccessoryItem("CARTA SIN ENVIAR — Professional Companion / Apoderado","No era mi carta y nunca pregunté por qué me la dejaron. La persona que me pagó para acompañarla aquella semana ya no vive aquí. A veces pienso que la carta habría explicado algo. O quizá sólo habría complicado las cosas.",0.015,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),35));
        put(m,"V881_ELECTROMECHANIC|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLACA DE DIAGNÓSTICO — V881 Electromechanic / Intelectual","La primera máquina que reparé volvió a funcionar durante seis meses antes de fallar por otra cosa. Guardo la placa porque fue la primera vez que entendí que arreglar algo no significa conocerlo entero.",0.060,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"DOMESTIC_V881_INSTALLER|LUCHADOR",new PricedAccessory(new AccessoryItem("AISLANTE MARCADO — Domestic V881 Installer / Luchador","Lo marqué después de encontrar una derivación defectuosa detrás de una pared. No era una pieza valiosa. Me recuerda que muchas reparaciones importantes empiezan con algo que nadie puede ver.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"FREQUENCY_INSTRUMENT_MAKER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("RESONADOR DESCARTADO — Frequency Instrument Maker / Especialista","Lo guardo porque no parece defectuoso. Ése era precisamente el problema. Tuve que aprender a reconocer el fracaso antes de que pudiera verse.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),75));
        put(m,"MATRIX_ARCHITECT|INTELECTUAL",new PricedAccessory(new AccessoryItem("FRAGMENTO DE MATRIZ RECHAZADA — Matrix Architect / Intelectual","La guardo porque sabía que no servía. No por nostalgia. Quería recordar exactamente dónde había empezado a introducirse el error.",0.070,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),85));
        put(m,"KINGDOM_MESSENGER|INTELECTUAL",new PricedAccessory(new AccessoryItem("SELLO DE CADENA DE CUSTODIA — KINGDOM_MESSENGER / INTELECTUAL","Lo guardo porque fue la primera pieza que me enseñó que un mensaje no vale sólo por llegar: también importa poder demostrar por dónde pasó.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"CYCLIST_MESSENGER|INDOMITO",new PricedAccessory(new AccessoryItem("TIMBRE DE LA PRIMERA RUTA — CYCLIST_MESSENGER / INDOMITO","Lo conservo aunque ya no uso esta bicicleta. Su sonido me devuelve a la primera ruta que hice sin perder una entrega.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"FREQUENCY_PHYSICIAN|ESPECIALISTA",new PricedAccessory(new AccessoryItem("LÁMINA DE DIAGNÓSTICO — FREQUENCY_PHYSICIAN / ESPECIALISTA","La guardo porque fue la primera lectura en la que una firma dejó de ser ruido y se convirtió en una decisión clínica.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),44));
        put(m,"SURGEON|LUCHADOR",new PricedAccessory(new AccessoryItem("PINZA DE LA PRIMERA CIRUGÍA — SURGEON / LUCHADOR","La guardo porque aquella intervención me enseñó que una mano firme no basta: también hay que saber exactamente cuándo detenerla.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),52));
        put(m,"VETERINARIAN|APODERADO",new PricedAccessory(new AccessoryItem("PLACA DE UNA CUADRA — VETERINARIAN / APODERADO","La guardo porque perteneció al primer animal que traté sin que su dueño pudiera pagarme por completo. La deuda quedó saldada de otra manera.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),35));
        put(m,"FREQUENCY_RESEARCHER|INTELECTUAL",new PricedAccessory(new AccessoryItem("CUADERNO DE CONTROLES — FREQUENCY_RESEARCHER / INTELECTUAL","Lo guardo porque las páginas muestran más controles fallidos que resultados. Son la parte del experimento que más me enseñó.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),48));
        put(m,"ELECTROATMOSPHERIC_NETWORK_ENGINEER|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLANO DE UNA RED — ELECTROATMOSPHERIC_NETWORK_ENGINEER / INTELECTUAL","Lo guardo porque fue la primera red que diseñé sin que una descarga terminara recordándome que el cielo también forma parte de la instalación.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),55));
        put(m,"ELECTROATMOSPHERIC_CAPTATION_ENGINEER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CONTACTO DE CAPTACIÓN — ELECTROATMOSPHERIC_CAPTATION_ENGINEER / ESPECIALISTA","Lo guardo porque una diferencia que nadie veía a simple vista decidió cuánto podía entregar una superficie.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),46));
        put(m,"ELECTROATMOSPHERIC_SAFETY_ENGINEER|MAESTRO",new PricedAccessory(new AccessoryItem("PLACA DE AISLAMIENTO — ELECTROATMOSPHERIC_SAFETY_ENGINEER / MAESTRO","Yo la guardo por la primera red que tuve que detener. Mi compañera la conserva por la reapertura que sólo autorizó después de revisar cada informe.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),72));
        put(m,"ELECTROMAGNETIC_LOCOMOTION_SYSTEMS_ENGINEER|INTELECTUAL",new PricedAccessory(new AccessoryItem("BOBINA DE ENSAYO — ELECTROMAGNETIC_LOCOMOTION_SYSTEMS_ENGINEER / INTELECTUAL","La guardo porque fue el componente que me enseñó que una locomotora puede parecer estable hasta que se mide la secuencia correcta.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),50));
        put(m,"RAILWAY_INFRASTRUCTURE_ENGINEER|MAESTRO",new PricedAccessory(new AccessoryItem("CLAVO DE LA PRIMERA ESTACIÓN — RAILWAY_INFRASTRUCTURE_ENGINEER / MAESTRO","Yo lo guardo de la primera estación que proyecté. Mi compañera lo conserva porque aquella estación fue la primera que obligó a reorganizar un asentamiento entero.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),68));
        put(m,"ELECTROMAGNETIC_TRANSPORT_PLANNER|HERALDO",new PricedAccessory(new AccessoryItem("MAPA DE UNA LÍNEA — ELECTROMAGNETIC_TRANSPORT_PLANNER / HERALDO","Lo guardo porque alrededor de esta línea aparecieron personas antes de que aparecieran los edificios que habíamos dibujado.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),61));
        put(m,"SANITARY_MASTER|MAESTRO",new PricedAccessory(new AccessoryItem("LLAVE DE CORTE SANITARIO — SANITARY_MASTER / MAESTRO","Yo la conservo de la primera red que tuve que aislar. Mi compañera la guarda porque después siguió durante meses a las familias afectadas.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),64));
        put(m,"FORESTRY_MANAGER|APODERADO",new PricedAccessory(new AccessoryItem("MARCA DE ORDENACIÓN FORESTAL — FORESTRY_MANAGER / APODERADO","La guardo porque aprendí a distinguir un bosque que produce hoy de uno que seguirá existiendo cuando yo ya no tenga que administrarlo.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),39));
        put(m,"PROSPECTOR|INDOMITO",new PricedAccessory(new AccessoryItem("PIEDRA DE LA PRIMERA MUESTRA — PROSPECTOR / INDOMITO","La guardo porque no parecía contener nada. Dos meses después había cambiado el mapa económico de toda la comarca.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),47));
        put(m,"REGENERATIONIST|MAESTRO",new PricedAccessory(new AccessoryItem("REGISTRO DE REGENERACIÓN — REGENERATIONIST / MAESTRO","Yo guardo este registro por una intervención que no podía repetirse. Mi compañera lo conserva por el seguimiento de años que evitó perder una adaptación útil.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),86));
        put(m,"CONTINUITY_EPIGENETICIST|MAESTRO",new PricedAccessory(new AccessoryItem("PORTA-MUESTRAS DE LINAJE — CONTINUITY_EPIGENETICIST / MAESTRO","Yo lo conservo por la primera desviación que detecté. Mi compañera lo conserva por la generación posterior que demostró que aquella desviación importaba.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),92));
        put(m,"NEUROARCHITECT|MAESTRO",new PricedAccessory(new AccessoryItem("MAPA NEURONAL PLEGADO — NEUROARCHITECT / MAESTRO","Yo lo guardo por la primera arquitectura que conseguí cartografiar. Mi compañera lo conserva por el patrón autobiográfico que sólo apareció después de años.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),98));
        put(m,"SOUL_RESEARCHER|MAESTRO",new PricedAccessory(new AccessoryItem("PLACA DE FIRMA ÁLMICA — SOUL_RESEARCHER / MAESTRO","Yo la conservo por la primera firma reproducible. Mi compañera la conserva por el caso en que cuerpo y memoria dejaron de explicar por sí solos a la persona.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),105));
        put(m,"SOUL_TRANSFUSIONIST|MAESTRO",new PricedAccessory(new AccessoryItem("SELLO DE COMPATIBILIDAD — SOUL_TRANSFUSIONIST / MAESTRO","Yo lo guardo por un trasvase que terminó estable. Mi compañera lo conserva por el seguimiento que confirmó que la identidad había continuado después del cambio de soporte.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),115));
        put(m,"SILICIC_METAMORPHOSIS_RESEARCHER|MAESTRO",new PricedAccessory(new AccessoryItem("FRAGMENTO DE MATRIZ SILÍCICA — SILICIC_METAMORPHOSIS_RESEARCHER / MAESTRO","Yo lo guardo porque fue el primer fragmento estable. Mi compañera lo conserva porque fue el primero cuya configuración no borró la continuidad que intentábamos conservar.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),125));
        put(m,"PERMANENCE_RESEARCHER|MAESTRO",new PricedAccessory(new AccessoryItem("MARCA DE PERSISTENCIA — PERMANENCE_RESEARCHER / MAESTRO","Yo la conservo por el primer fenómeno que permaneció sin su soporte original. Mi compañera la conserva porque demostró que la persistencia también podía seguir una identidad.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),135));
        put(m,"ENLIGHTENED|MAESTRO",new PricedAccessory(new AccessoryItem("CUADERNO DEL INTERSTICIO — ENLIGHTENED / MAESTRO","Yo lo guardo por el lugar que sólo apareció una vez. Mi compañera lo conserva por la ruta que permitió volver a encontrar una configuración parecida sin asumir que era la misma.",0.050,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),150));
        // abalorios biográficos de Soldado y Mercenario. Cada perfil activo tiene uno.
        put(m,"V881_RIFLEMAN|LUCHADOR",new PricedAccessory(new AccessoryItem("FLECHA DE ALZA DEL FUSILERO — ","Conservo esta pieza porque fue lo primero que aprendí a revisar antes de salir a una línea. No me sirve como talismán: me recuerda que una mala comprobación puede costar mucho más que una bala.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"V881_CAMPAIGN_SAPPER|LUCHADOR",new PricedAccessory(new AccessoryItem("CUÑA DEL PRIMER ZAPADOR — ","La guardo porque quedó deformada durante mi primera obra bajo fuego. No la uso ya; me recuerda que el trabajo del zapador empieza antes de tocar una herramienta.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"V881_CAMPAIGN_SAPPER|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLANO MARCADO DEL ZAPADOR — ","Este plano conserva una corrección que hice después de encontrar un error en una instalación. Lo llevo para recordar que medir dos veces no es una formalidad.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),35));
        put(m,"V881_HEAVY_WEAPONS_SPECIALIST|LUCHADOR",new PricedAccessory(new AccessoryItem("PIEZA DE RECUPERACIÓN DE ARTILLERÍA — ","La conservo porque fue la primera pieza que tuve que sustituir con el arma todavía en servicio. Me recuerda cuánto pesa realmente una máquina cuando deja de funcionar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"V881_HEAVY_WEAPONS_SPECIALIST|INTELECTUAL",new PricedAccessory(new AccessoryItem("TABLA DE CÁLCULO BALÍSTICO — ","La guardo llena de anotaciones de mis primeros cálculos. No contiene ningún secreto; contiene errores corregidos y por eso sigue siendo útil para mí.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),32));
        put(m,"INSTITUTIONAL_SHOCK_COMBATANT|LUCHADOR",new PricedAccessory(new AccessoryItem("HEBILLA DE LA PRIMERA CARGA — ","La llevo desde una carga en la que la hebilla quedó doblada. No representa una victoria; representa que volví con todo lo que todavía podía llevar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),20));
        put(m,"INSTITUTIONAL_SHOCK_COMBATANT|INDOMITO",new PricedAccessory(new AccessoryItem("CORREA RASGADA DE CAMPAÑA — ","La guardo porque se rompió cuando tuve que abandonar una formación y seguir solo. Me recuerda que sobrevivir también consiste en saber cuándo dejar atrás el plan.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),15));
        put(m,"KINGDOM_AGENT|HERALDO",new PricedAccessory(new AccessoryItem("PLACA DE SERVICIO DEL REINO — ","La conservo porque fue la primera placa que llevé durante una intervención sin disparar. Me recuerda que representar una autoridad también significa saber cuándo no usarla.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),42));
        put(m,"V881_SUPPORT_MARKSWOMAN|ESPECIALISTA",new PricedAccessory(new AccessoryItem("AJUSTADOR DEL PRIMER VISOR — ","Guardo este pequeño ajustador porque con él aprendí a no culpar al arma por un error mío. Cada vez que lo veo recuerdo que la precisión empieza por revisar el procedimiento.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),30));
        put(m,"STRATEGIC_INSTALLATION_CUSTODIAN|APODERADO",new PricedAccessory(new AccessoryItem("LLAVE DE LA SALA DE CUSTODIA — ","La conservo porque abrió la primera instalación que me confiaron. No abre nada importante ahora; para mí representa la responsabilidad de cerrar una puerta a tiempo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),38));
        put(m,"RAILWAY_GUARD|HERALDO",new PricedAccessory(new AccessoryItem("BILLETE DE LA PRIMERA LÍNEA — ","Lo guardo porque fue el primer servicio ferroviario que custodié. Me recuerda que una línea no sólo transporta mercancías: también transporta confianza.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),25));
        put(m,"RAILWAY_GUARD|ESPECIALISTA",new PricedAccessory(new AccessoryItem("FICHA DE SEÑAL FERROVIARIA — ","La llevo porque aprendí a interpretar señales con esta ficha en la mano. Me recuerda que una pequeña indicación puede separar una rutina de un accidente.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),27));
        put(m,"COMPANY_CONTRACTOR|LUCHADOR",new PricedAccessory(new AccessoryItem("MARTILLO DEL PRIMER CONTRATO — ","Lo conservo porque fue la herramienta que llevé cuando acepté mi primer contrato completo. Me recuerda que un mercenario vende una capacidad concreta y debe responder por ella.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),26));
        put(m,"COMPANY_CONTRACTOR|INTELECTUAL",new PricedAccessory(new AccessoryItem("HOJA DE CONDICIONES DEL PRIMER CONTRATO — ","Guardo esta hoja porque aprendí a leer cada cláusula después de cobrar aquel primer trabajo. Me recuerda que un contrato también es una forma de logística.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),34));
        put(m,"CONTRACTUAL_SHOCK_COMBATANT|LUCHADOR",new PricedAccessory(new AccessoryItem("PLACA ABOLLADA DEL CONTRATO — ","La guardo porque terminó abollada durante un trabajo de ruptura. No demuestra que fuera mejor que nadie; demuestra que el contrato terminó y yo también.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),22));
        put(m,"CONVOY_ESCORT|INDOMITO",new PricedAccessory(new AccessoryItem("PRECINTO DE CONVOY — ","Lo llevo desde el primer convoy que escolté hasta destino. Me recuerda que mi trabajo empieza cuando la carga sale y termina cuando deja de estar bajo mi responsabilidad.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),16));
        put(m,"EXCEPTIONAL_ASSET_RECOVERER|LUCHADOR",new PricedAccessory(new AccessoryItem("FRAGMENTO DEL ACTIVO RECUPERADO — ","Conservo este fragmento porque fue la única parte que pude sacar con mis propias manos. Me recuerda que recuperar algo valioso casi nunca se parece a recogerlo del suelo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),45));
        put(m,"EXCEPTIONAL_ASSET_RECOVERER|INDOMITO",new PricedAccessory(new AccessoryItem("MARCA DE RUTA DE RECUPERACIÓN — ","La guardo porque señala una ruta que tuve que abandonar para poder volver vivo. Me recuerda que un activo no vale una vida perdida.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),32));
        put(m,"MERCENARY_COMPANY_DIRECTOR|INTELECTUAL",new PricedAccessory(new AccessoryItem("SELLO DE UNA COMPAÑÍA DISUELTA — ","Conservo este sello de una compañía que ya no existe. Me recuerda que una empresa mercenaria puede desaparecer mucho antes de que desaparezcan sus deudas.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),55));
        put(m,"MOTORCYCLE_COURIER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("LLAVE DE LA PRIMERA MOTOCICLETA — ","La guardo porque con esta llave hice mis primeras entregas. Me recuerda que una ruta rápida sólo sirve si la máquina llega contigo hasta el final.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),28));
        put(m,"FRONTIER_SKIRMISHER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CÁPSULA DE VISOR DE FRONTERA — ","La conservo porque perteneció al equipo con el que aprendí a trabajar a distancia. Me recuerda que reconocer primero suele ser más importante que disparar primero.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),31));
        put(m,"MOBILE_ESCORT|APODERADO",new PricedAccessory(new AccessoryItem("CREDENCIAL DEL PRIMER PROTEGIDO — ","La guardo porque perteneció a la primera persona cuya seguridad dependió de mí. Me recuerda que escoltar no consiste en caminar al lado de alguien, sino en anticiparse.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),39));
        put(m,"MOBILE_ESCORT|HERALDO",new PricedAccessory(new AccessoryItem("CARTA DE CONFIANZA DEL PROTEGIDO — ","Conservo esta carta porque fue la primera vez que alguien volvió a contratarme por recomendación. Me recuerda que la reputación también forma parte del trabajo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),44));
        put(m,"TECHNICAL_RECOVERY_OPERATOR|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CONECTOR DEL PRIMER ACTIVO TÉCNICO — ","Lo guardo porque perteneció al primer sistema que recuperé sin dañarlo. Me recuerda que desmontar deprisa es fácil; desmontar sin destruir exige oficio.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),48));
        put(m,"TECHNICAL_RECOVERY_OPERATOR|APODERADO",new PricedAccessory(new AccessoryItem("PRECINTO DE CUSTODIA TÉCNICA — ","Lo conservo porque fue colocado sobre mi primer activo recuperado antes de transportarlo. Me recuerda que poseer algo temporalmente también implica responder por su integridad.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),43));
        put(m,"SABOTAGE_DENIAL_SPECIALIST|ESPECIALISTA",new PricedAccessory(new AccessoryItem("PIEZA DE LA PRIMERA NEGACIÓN — ","La guardo porque fue retirada de un sistema que ya no podía seguir funcionando. Me recuerda que sabotear no significa destruir al azar, sino negar exactamente la capacidad contratada.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),46));
        put(m,"SABOTAGE_DENIAL_SPECIALIST|APODERADO",new PricedAccessory(new AccessoryItem("CLAVE DE ACCESO DEL PRIMER OBJETIVO — ","La conservo porque abrió el primer lugar que tuve que inutilizar. Me recuerda que el acceso suele ser más valioso que la fuerza.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),40));
        put(m,"SHOPKEEPER|APODERADO",new PricedAccessory(new AccessoryItem("LLAVE DEL PRIMER MOSTRADOR — ","La conservo porque abrió el primer local que pude mantener sin ayuda. Me recuerda que vender algo cada día no significa que el negocio esté seguro.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),26));
        put(m,"TAVERN_KEEPER|APODERADO",new PricedAccessory(new AccessoryItem("JARRA DEL PRIMER LOCAL — ","La guardo porque fue de la primera noche que tuve que resolver compras, existencias y cuentas a la vez. Me recuerda que una taberna se sostiene también cuando nadie está mirando.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),32));
        put(m,"TAVERN_KEEPER|HERALDO",new PricedAccessory(new AccessoryItem("FICHA DE LA PRIMERA MESA — ","La llevo porque perteneció a la mesa donde dos clientes que no se soportaban terminaron compartiendo una noche tranquila. Me recuerda que parte de mi oficio es hacer posible esa convivencia.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),38));
        put(m,"BOOKSELLER|INTELECTUAL",new PricedAccessory(new AccessoryItem("MARCAPÁGINAS DEL VOLUMEN IMPOSIBLE — ","Lo conservo porque pasó años dentro de un libro que nadie conseguía localizar. Me recuerda que un catálogo también está hecho de ausencias.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),44));
        put(m,"RURAL_AGGREGATOR|INDOMITO",new PricedAccessory(new AccessoryItem("PRECINTO DE LA PRIMERA CARGA RURAL — ","Lo guardo porque cerró la primera carga que llevé de una explotación a un almacén. Me recuerda que el trabajo termina cuando la mercancía llega, no cuando sale.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"RURAL_AGGREGATOR|APODERADO",new PricedAccessory(new AccessoryItem("FICHA DE PRODUCTOR — ","La conservo porque pertenece al primer productor que volvió a confiar en mí después de una mala temporada. Me recuerda que una red comercial se construye cuando alguien decide volver a entregar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),29));
        put(m,"V881_INDUSTRIAL_BROKER|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLACA DE REPUESTO INDUSTRIAL — ","La guardo porque fue la pieza que me permitió evitar que una instalación quedara parada. Me recuerda que mi oficio consiste en conocer la cadena antes de que falle.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),46));
        put(m,"V881_INDUSTRIAL_CONTRACT_AGENT|APODERADO",new PricedAccessory(new AccessoryItem("SELLO DEL PRIMER CONTRATO INDUSTRIAL — ","Lo conservo porque cerró el primer contrato en el que tuve que traducir una necesidad técnica para dos partes que hablaban lenguajes distintos. Me recuerda que una cláusula también puede mantener una máquina funcionando.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),52));
        put(m,"V881_INDUSTRIAL_CONSULTANT|ESPECIALISTA",new PricedAccessory(new AccessoryItem("CALIBRADOR DE LA PRIMERA AUDITORÍA — ","Lo guardo porque lo utilicé para encontrar una tolerancia que estaba costando meses de producción. Me recuerda que una diferencia pequeña puede sostener una fábrica entera.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),58));
        put(m,"V881_INDUSTRIALIST|INTELECTUAL",new PricedAccessory(new AccessoryItem("PIEZA DE LA PRIMERA LÍNEA — ","La conservo porque perteneció a la primera línea de producción que conseguí estabilizar. Me recuerda que producir repetidamente es más difícil que fabricar una sola pieza.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),65));
        put(m,"V881_INDUSTRIALIST|APODERADO",new PricedAccessory(new AccessoryItem("SELLO DE CONTINUIDAD DE TALLER — ","Lo guardo porque lo utilizábamos para cerrar entregas cuando el taller atravesaba una crisis. Me recuerda que dirigir patrimonio también significa sostener salarios y proveedores cuando la producción cae.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),62));
        put(m,"SHIPOWNER|INTELECTUAL",new PricedAccessory(new AccessoryItem("ASTILLA DE LA PRIMERA RUTA — ","La conservo porque procede del primer barco cuya ruta calculé de principio a fin. Me recuerda que una nave sólo vale lo que puede sostener en el tiempo.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),70));
        put(m,"SHIPOWNER|APODERADO",new PricedAccessory(new AccessoryItem("LLAVE DE CAMAROTE DEL PRIMER BUQUE — ","La guardo porque perteneció al primer buque que tuve que mantener como patrimonio durante una temporada mala. Me recuerda que un barco sigue costando aunque permanezca amarrado.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),66));
        put(m,"FINANCIER|INTELECTUAL",new PricedAccessory(new AccessoryItem("PAGARÉ DE LA PRIMERA INVERSIÓN — ","Lo conservo porque fue la primera deuda cuyo riesgo calculé por completo. Me recuerda que prestar dinero significa decidir hoy sobre algo que todavía no ha ocurrido.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),78));
        put(m,"FINANCIER|APODERADO",new PricedAccessory(new AccessoryItem("LLAVE DE LA PRIMERA CAJA DE GARANTÍAS — ","La guardo porque abrió la primera caja de garantías que administré. Me recuerda que la confianza financiera siempre necesita algo que pueda responder cuando el futuro falla.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),74));
        put(m,"INFRASTRUCTURE_CONCESSIONAIRE|APODERADO",new PricedAccessory(new AccessoryItem("SELLO DE LA PRIMERA CONCESIÓN — ","Lo conservo porque autorizó una infraestructura que todavía sigue funcionando. Me recuerda que una firma puede convertirse en geografía mucho después de que quien la estampó haya desaparecido.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),92));
        put(m,"INFRASTRUCTURE_CONCESSIONAIRE|HERALDO",new PricedAccessory(new AccessoryItem("PLACA DE LA PRIMERA APERTURA — ","La guardo porque perteneció a la apertura de una instalación que tuvo que ser aceptada por quienes vivirían alrededor. Me recuerda que una obra no está terminada cuando funciona, sino cuando puede convivir con su entorno.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),88));
        put(m,"GRAND_MERCHANT|INTELECTUAL",new PricedAccessory(new AccessoryItem("MAPA DE LA PRIMERA CADENA — ","Lo conservo porque fue el primer mapa en el que una mercancía apareció como cadena completa y no como una sola venta. Me recuerda que el comercio grande empieza cuando dejas de mirar sólo el mostrador.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),105));
        put(m,"GRAND_MERCHANT|APODERADO",new PricedAccessory(new AccessoryItem("CARTA DEL PRIMER AGENTE — ","La guardo porque fue la primera persona que aceptó representar mis intereses lejos de mi territorio. Me recuerda que una red comercial existe porque otras personas deciden sostenerla.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),98));
        put(m,"RESTRICTED_MATERIALS_BROKER|INTELECTUAL",new PricedAccessory(new AccessoryItem("ETIQUETA DE LA PRIMERA MUESTRA RESTRINGIDA — ","La conservo porque acompañó una muestra cuya procedencia tuve que reconstruir durante meses. Me recuerda que cuando el material es escaso, la historia del objeto también forma parte de su valor.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),118));
        put(m,"RESTRICTED_MATERIALS_BROKER|APODERADO",new PricedAccessory(new AccessoryItem("PRECINTO DE CUSTODIA RESTRINGIDA — ","Lo guardo porque cerró el primer contenedor que tuve que entregar bajo una cadena de custodia completa. Me recuerda que mover algo valioso también significa responder por cada mano que lo toca.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),110));
        put(m,"PUBLIC_SCRIBE|INTELECTUAL",new PricedAccessory(new AccessoryItem("PLUMA DEL PRIMER ACTA — ","La conservo porque fue la pluma con la que redacté mi primer acto público completo. Me recuerda que una fecha correcta puede durar más que quien la escribe.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),34));
        put(m,"PUBLIC_SCRIBE|ESPECIALISTA",new PricedAccessory(new AccessoryItem("REGLA DE COTEJO DEL ESCRIBANO — ","La guardo porque me ayudó a detectar mi primer error documental antes de que llegara a una firma. Me recuerda que en mi oficio la precisión no admite correcciones invisibles.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),31));
        put(m,"MAGISTRATE|INTELECTUAL",new PricedAccessory(new AccessoryItem("SELLO DE LA PRIMERA RESOLUCIÓN — ","Lo conservo porque acompañó la primera resolución que tuve que justificar por escrito. Me recuerda que interpretar una norma obliga a aceptar que otros vivirán con el resultado.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),57));
        put(m,"MAGISTRATE|HERALDO",new PricedAccessory(new AccessoryItem("CARTA DEL PRIMER CASO — ","La guardo porque fue escrita por alguien que no estaba de acuerdo con mi decisión y aun así aceptó seguir hablando conmigo. Me recuerda que una autoridad pierde parte de su función cuando deja de escuchar.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),61));
        put(m,"CONTINUITY_JURIST|INTELECTUAL",new PricedAccessory(new AccessoryItem("FRAGMENTO DEL PRIMER EXPEDIENTE DE CONTINUIDAD — ","Lo conservo porque fue el primer expediente en el que cuerpo y persona dejaron de coincidir de una manera jurídicamente sencilla. Me recuerda que la identidad también necesita una historia documental.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),82));
        put(m,"CONTINUITY_JURIST|APODERADO",new PricedAccessory(new AccessoryItem("MEDALLA DE IDENTIDAD JURÍDICA — ","La guardo porque perteneció a la primera persona cuya continuidad tuve que defender durante una transformación. Me recuerda que sostener una identidad también significa sostener sus obligaciones.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),79));
        put(m,"DOCTRINE_CUSTODIAN|INTELECTUAL",new PricedAccessory(new AccessoryItem("FICHA DEL PRIMER ARCHIVO RESTRINGIDO — ","La conservo porque fue la primera pieza que tuve que clasificar sin publicarla. Me recuerda que administrar conocimiento también exige decidir cómo dejar constancia de una restricción.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),96));
        put(m,"DOCTRINE_CUSTODIAN|HERALDO",new PricedAccessory(new AccessoryItem("CARTA DE PUBLICACIÓN CONDICIONADA — ","La guardo porque fue la primera publicación que tuve que liberar sólo bajo determinadas condiciones. Me recuerda que comunicar una verdad también implica pensar en quién la recibe.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),101));
        put(m,"COMPETITION_RIDER|INDOMITO",new PricedAccessory(new AccessoryItem("HEBILLA DE LA PRIMERA CARRERA — ","La guardo porque la correa se rompió antes de mi primera salida importante y tuve que repararla con las manos temblando. No gané aquella carrera. Aprendí qué parte de la montura reviso ahora dos veces.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),34));
        put(m,"V881_MOTORCYCLE_RACER|ESPECIALISTA",new PricedAccessory(new AccessoryItem("PLACA RASPADA DE CARENADO — ","La guardo porque tocó el suelo antes que yo. El arañazo empieza exactamente donde elegí mal la entrada de una curva. No necesito borrarlo para saber conducir mejor.",0.080,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),56));
        put(m,"COMPETITION_CYCLIST|ESPECIALISTA",new PricedAccessory(new AccessoryItem("ESLABÓN DE CADENA MARCADO — ","Lo guardo porque fue el eslabón que casi me dejó fuera de una carrera lejos de casa. Desde entonces limpio la transmisión aunque esté cansada y todos los demás ya se hayan ido a dormir.",0.020,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),18));
        put(m,"TRIATHLETE|INDOMITO",new PricedAccessory(new AccessoryItem("FICHA DE CONTROL DE TRES TRAMOS — ","La llevo porque fue la primera vez que llegué al último tramo sin sentir que estaba empezando de nuevo. Está doblada y casi no se lee, pero todavía recuerdo dónde pensé en abandonar.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),12));
        put(m,"COMPANION_ANIMAL_BREEDER|INTELECTUAL",new PricedAccessory(new AccessoryItem("COLLAR DE LA PRIMERA CAMADA — ","Lo guardo porque perteneció al primer animal que decidí no reproducir. Era sano y cariñoso, pero transmitía un miedo que tardé meses en reconocer. Aquella decisión me enseñó más que cualquier venta.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),31));
        // afinidades absorbidas por Agricultor/Ganadero conservan abalorio profesional propio.
        put(m,"FARMER|INDOMITO",new PricedAccessory(new AccessoryItem("CORDÓN DE LA PRIMERA COSECHA — Agricultor / Indómito","Lo guardo porque ataba el primer haz que coseché sin que nadie tuviera que repetir una instrucción. No tiene valor por el material; para mí marca el día en que dejé de limitarme a ayudar y empecé a responder por una parcela.",0.010,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),14));
        put(m,"LIVESTOCK_KEEPER|APODERADO",new PricedAccessory(new AccessoryItem("HEBILLA DE LA PRIMERA RES — Ganadero / Apoderado","La conservo porque perteneció al primer animal cuya pérdida tuve que asumir como responsabilidad propia. Me recuerda que cuidar ganado no consiste sólo en poseerlo: también significa responder por lo que depende de ti.",0.030,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),24));
        put(m,"LIVESTOCK_KEEPER|HERALDO",new PricedAccessory(new AccessoryItem("CENCERRO SIN BADAJO — Ganadero / Heraldo","Lo guardo porque aprendí a reconocer a todo el rebaño antes de necesitar oírlo. Cuando trato con compradores o vecinos me recuerda que conocer lo que representas es más importante que hablar más alto.",0.040,new InventoryFootprint(1,1),List.of(),List.of(),List.of()),27));
        return Map.copyOf(m);
    }
    private static void put(Map<String,PricedAccessory> m,String k,PricedAccessory v){
        if(m.put(k,v)!=null) throw new IllegalStateException("Abalorio ocupacional duplicado: "+k);
    }
}
