package domain.character.progression;

/** Corpus canónico : la inspección conserva voz narrativa y Transposición expone el Grimorio técnico. */
public final class MucusDoctrine {
    private MucusDoctrine() {}

    public static final String CURSE_AND_MUCUS =
            "NOMBRE COMPLETO: Energía Maldita · NOMBRE MECÁNICO: Maldición. La Energía Maldita es un canal de fuerza que nace de la fricción entre la biomáquina y la adversidad. No es luz, ni calor, ni electricidad ordinaria: es la impresión persistente que deja en la materia viva la tensión, el daño y la adaptación forzada. Cuando esa impresión se libera, se manifiesta como Maldición.\n\n" +
            "ORIGEN FISIOLÓGICO Y ANTROPOMÉTRICO | Toda experiencia límite altera la homeostasis del organismo. En el duodeno —cruce entre estómago e intestino delgado— convergen secreciones digestivas, absorción de nutrientes, flujo sanguíneo visceral y un denso plexo nervioso. Es el punto donde la química del cuerpo se transforma en información utilizable. Bajo una odisea, el sistema nervioso y el aparato endocrino liberan mensajeros que reescriben funciones, tejidos y prioridades vitales. El residuo de esa reescritura se condensa como mucus. En su estado original, ese residuo es inestable y corrosivo: contiene la energía destructiva de la ruptura que lo originó.\n\n" +
            "FUNCIONAMIENTO DE LA MALDICIÓN | La Maldición no es un objeto, sino un vector de imposición. Puede propagarse mediante contacto, impacto, herramientas, símbolo o intención, y su efecto depende de tres factores: INTENSIDAD, la cantidad de Energía Maldita canalizada; COHERENCIA, la claridad con que la intención se imprime; y AFINIDAD, la compatibilidad entre la fuente y el receptor. Sus manifestaciones conocidas incluyen daño maldito, drenaje vital, degradación de atributos, sellos, confusión, Frenesí y reescritura temporal de funciones.\n\n" +
            "RELACIÓN ENTRE LA MALDICIÓN Y EL MUCUS | El mucus no es la Maldición, pero contiene la memoria biológica y material de aquello que la genera. Cuanto mayor es la odisea, más densa y estable es esa memoria. Así, el mucus es al individuo lo que la Maldición es al mundo: potencial de transformación. ADVERSIDAD → RUPTURA → ADAPTACIÓN → MUCUS → MALDICIÓN.";

    public static final String CURSE_NATURE =
            "La Maldición no es maldad ni castigo: es la huella de toda ruptura profunda. Lo que corrompe también puede crear. El Maestro se limita a comprender sus leyes para no ser devorado por ellas.";

    public static final String TYPES_HEADER =
            "El mucus es la memoria material de cada odisea. Su aspecto revela la profundidad de la adaptación y su reserva se mide en mililitros: no como rareza abstracta, sino como volumen máximo que la biomáquina puede estabilizar simultáneamente en ese estado. Blanco 2.000 mL; Amarillento 500 mL; Verdoso 100 mL; Marrón 25 mL; Ensangrentado 5 mL; Negruzco 1 mL. Cuanto más peligroso es el estado fisiológico que dejó esa memoria, menor es el volumen compatible con conservar la continuidad del organismo.\n\nSin desafío no existe mucus. La misma adversidad en tiempos distintos puede no dejar rastro alguno.";

    public static String informal(MucusType type) {
        return switch (type) {
            case BLANCO -> "El cuerpo aprende primero a conservarse. Antes de desarrollar nuevas capacidades, reorganiza silenciosamente sus funciones esenciales para mantener la vida frente al desgaste cotidiano. El Mucus Blanco representa esa adaptación primaria: la respuesta fisiológica destinada a preservar la integridad del organismo incluso cuando ninguna otra especialización resulta todavía necesaria. El mucus es una secreción natural, producto de la oxidación de la bioquímica. Suele ser transparente y muy líquido, fruto de circunstancias generalmente benignas y transitorias. RESERVA MÁXIMA: 2.000 mL.";
            case AMARILLENTO -> "La supervivencia exige algo más que permanecer con vida. Exige continuar avanzando cuando el agotamiento intenta detener cada movimiento. El Mucus Amarillento surge cuando el organismo aprende a administrar mejor sus reservas energéticas, refinando la resistencia y el esfuerzo prolongado hasta convertirlos en una segunda naturaleza. La adquisición de la verdadera fuerza comienza con este tipo de mucus, sabroso para el paladar. RESERVA MÁXIMA: 500 mL.";
            case VERDOSO -> "No toda adaptación consiste en resistir. Algunas nacen de la necesidad de cambiar. El Mucus Verdoso aparece cuando el organismo aprende a reorganizarse frente a condiciones variables, incorporando nuevas respuestas antes de que el entorno termine por imponerse. Su existencia refleja la capacidad del cuerpo para modificar su propio equilibrio sin perder estabilidad. La pegajosidad de este tipo de mucus indica que la biomáquina recordará la odisea incluso en sus días más tranquilos. RESERVA MÁXIMA: 100 mL.";
            case MARRON -> "Todo peso deja una huella sobre quien decide cargarlo. El Mucus Marrón representa la adaptación progresiva frente al esfuerzo físico continuado, fortaleciendo la estructura que sostiene el cuerpo hasta convertir el trabajo repetido en una condición asumida por el propio organismo. El mucus de la biomáquina llevada al fallo orgánico parcial. El crecimiento nunca es lineal y los tipos de mucus son una prueba de ello. RESERVA MÁXIMA: 25 mL.";
            case ENSANGRENTADO -> "Hay heridas que no destruyen el cuerpo; lo obligan a reconstruirse de otra manera. El Mucus Ensangrentado nace cuando la supervivencia depende de reorganizar tejidos, recuperar funciones y continuar luchando pese al daño recibido. Conserva la memoria fisiológica de haber permanecido en pie cuando el organismo estuvo cerca de ceder. El mucus de una biomáquina llevada al límite. Si uno no se renuncia a sí mismo, uno no será capaz de merecerse a sí mismo. RESERVA MÁXIMA: 5 mL.";
            case NEGRUZCO -> "Algunas transformaciones no afectan únicamente al cuerpo, sino también a la forma en que este interpreta el mundo. El Mucus Negruzco aparece cuando la experiencia obliga al organismo a desarrollar respuestas fisiológicas frente a fenómenos que escapan a una percepción ordinaria. Es la manifestación más excepcional de todas las adaptaciones fisiológicas. ¡La verdad está en el mucus! Su negrura remite al límite biológico en el que necrosis, material degradado o invasión fúngica dejan de ser una alteración local y pueden comprometer percepción, conducta y continuidad del yo. La biomáquina sólo admite 1 mL de esta memoria estabilizada: más allá, la adaptación correría el riesgo de convertirse en colonización por aquello que debía sobrevivirse. El mucus negruzco recuerda que incluso cuando el soporte empieza a dejar de obedecer, todavía debe quedar alguien capaz de reconocerse. ¡La verdad está en el mucus! RESERVA MÁXIMA: 1 mL.";
        };
    }

    public static String transpositionKnowledge(MucusType type) {
        return switch (type) {
            case BLANCO -> "LÁGRIMA DE MUCUS BLANCO | La superficie ocular se conserva mediante una película lagrimal cuyo componente mucoso mantiene estable la interfaz entre tejido y mundo. Durante el reposo, al cesar el barrido del parpadeo, mucus, lípidos, células y residuos pueden acumularse. TRANSPOSICIÓN separa esa lógica protectora de la superficie viva y la estabiliza como una lágrima: una película capaz de transportar temporalmente memoria biológica a materia inerte. Cada 1 mL transpuesto genera una Lágrima; se apilan hasta 100 por ranura.";
            case AMARILLENTO -> "CRISTAL AMARILLENTO · TETRAEDRO | La respuesta inflamatoria delimita una frontera entre organismo y agresión. El tetraedro es la mínima organización tridimensional cerrada capaz de diferenciar polos: fija la primera memoria superior de separación y la convierte en una frontera estable frente a Veneno y Toxicidad Virulenta.";
            case VERDOSO -> "CRISTAL VERDOSO · OCTAEDRO | La memoria de una respuesta celular intensa se estabiliza como dos pirámides opuestas en equilibrio. El octaedro conserva la dualidad entre carga térmica y recuperación homeostática y la inmoviliza como inmunidad frente a Quemadura Asfixiante.";
            case MARRON -> "CRISTAL MARRÓN · CUBO | El fallo orgánico parcial aparece cuando deformaciones y costes se propagan entre subsistemas. El cubo introduce ejes ortogonales y regiones diferenciadas: estabiliza el último estado anterior al agotamiento y evita que una inhibición de PA REGEN llegue a consolidarse.";
            case ENSANGRENTADO -> "CRISTAL ENSANGRENTADO · ESFERA | Cuando la biomáquina ha sido llevada al límite, la memoria relevante ya no pertenece a una región: pertenece a la forma corporal completa que intenta reconstruirse. La esfera no privilegia ningún punto ni dirección; fija una configuración global y evita que una Maldición externa imponga otra como nuevo equilibrio.";
            case NEGRUZCO -> "CRISTAL NEGRUZCO · DODECAEDRO | La memoria de mayor peligrosidad no protege una sola función, sino la continuidad entre múltiples regiones perceptivas y cognitivas. El dodecaedro, como poliedro complejo de regiones especializadas, estabiliza esa coherencia y hace que Frenesí no encuentre una estructura mental sobre la que imponerse.";
        };
    }

    public static final String CRYSTALLIZATION =
            "A medida que la memoria adaptativa se vuelve más rara, su estructura se densifica y estabiliza hasta cristalizar en una forma capaz de preservarla sin degradación. Cada cristal inmoviliza una propiedad adaptativa y la convierte en una inmunidad permanente mientras permanezca equipado. La forma no es ornamental: cada memoria sólo permanece estable en una geometría compatible con la organización que la originó.";
}
