package domain.control;

import java.util.List;

public final class PcControlScheme {
    private PcControlScheme() {
    }

    public static List<ControlBinding> canonicalBindings() {
        return List.of(
                new ControlBinding("W/A/S/D", InputGesture.PRESS, ControlAction.MOVE, ""),
                new ControlBinding("MOVER RATÓN", InputGesture.PRESS_WITH_DIRECTION, ControlAction.MOVE_CAMERA, "Control de cámara"),
                new ControlBinding("SHIFT", InputGesture.HOLD, ControlAction.RUN, ""),
                new ControlBinding("C", InputGesture.PRESS, ControlAction.SLIDE, "MIENTRAS CORRE: deslizamiento frontal de 1,5 × altura; prevalece contextualmente sobre cambio de postura"),
                new ControlBinding("C", InputGesture.PRESS, ControlAction.DIVE, "EN AGUA: bucear; prevalece contextualmente sobre postura y consume 1 PA/s"),
                new ControlBinding("C", InputGesture.PRESS, ControlAction.CYCLE_STANCE, "Fuera de carrera: Trotar → Agacharse → Gatear → Trotar"),
                new ControlBinding("C", InputGesture.HOLD, ControlAction.WALK, ""),
                new ControlBinding("SPACE", InputGesture.PRESS_WITH_DIRECTION, ControlAction.FEINT, "Dirección opcional"),
                new ControlBinding("SPACE", InputGesture.DOUBLE_PRESS, ControlAction.JUMP, ""),
                new ControlBinding("RIGHT CLICK", InputGesture.PRESS, ControlAction.JUMP_ATTACK, "Solo en el aire"),
                new ControlBinding("E", InputGesture.PRESS, ControlAction.INTERACT, "Solo con hitbox frontal dentro del alcance antropométrico"),
                new ControlBinding("E", InputGesture.PRESS, ControlAction.TOGGLE_OBSERVATION_MARK,
                        "MONOCULAR ACTIVO: coloca/sustituye la única marca de observación; prevalece contextualmente sobre INTERACT"),
                new ControlBinding("Q", InputGesture.PRESS, ControlAction.CYCLE_CONTEXTUAL_ACTION, "Solo entre acciones de una hitbox alcanzable"),
                new ControlBinding("Q", InputGesture.PRESS, ControlAction.SWITCH_WEAPON, "Sin interacción abierta; Q conserva la familia de acciones contextuales"),
                new ControlBinding("TAB", InputGesture.PRESS, ControlAction.SHEATHE_OR_UNSHEATHE, "Estado de combate: envainar/desenvainar"),
                new ControlBinding("MOUSE WHEEL UP", InputGesture.WHEEL_FORWARD, ControlAction.MONOCULAR_ZOOM_IN,
                        "MONOCULAR ACTIVO: ×3 → ×4 → ×5; ×5 es guardarraíl duro"),
                new ControlBinding("MOUSE WHEEL DOWN", InputGesture.WHEEL_BACKWARD, ControlAction.MONOCULAR_ZOOM_OUT,
                        "MONOCULAR ACTIVO: ×5 → ×4 → ×3; ×3 es guardarraíl duro"),
                new ControlBinding("MOUSE WHEEL", InputGesture.WHEEL_CLICK, ControlAction.TOGGLE_SHAPESHIFT,
                        "ASPIRANT/ANCIENT con CAMBIAFORMAS: alterna forma humana y forma cambiada; prevalece contextualmente sobre configuración de arma/modo de fuego"),
                new ControlBinding("MOUSE WHEEL", InputGesture.WHEEL_CLICK, ControlAction.CYCLE_WEAPON_CONFIGURATION,
                        "Recorre combinaciones válidas de empuñadura y modo de acción"),
                new ControlBinding("MOUSE WHEEL", InputGesture.WHEEL_CLICK, ControlAction.CYCLE_FIRE_MODE,
                        "ARMAS DE FUEGO: cambia 1A / 3A / AA entre las cadencias disponibles"),
                new ControlBinding("LEFT CLICK", InputGesture.PRESS, ControlAction.TOGGLE_FIREARM_AIM,
                        "Solo firearms con AIMING; Lanza-Arcos, Rociador y arrojadizos no lo utilizan"),
                new ControlBinding("LEFT CLICK", InputGesture.PRESS, ControlAction.TOGGLE_RANGED_WEAPON_AIM,
                        "HONDA Y ARCOS: activa o desactiva AIMING"),
                new ControlBinding("RIGHT CLICK", InputGesture.PRESS, ControlAction.FIRE_RANGED_WEAPON,
                        "HONDA Y ARCOS: disparo 1A; respeta recuperación y munición compatible"),
                new ControlBinding("RIGHT CLICK", InputGesture.PRESS, ControlAction.FIRE_FIREARM,
                        "ARMAS DE FUEGO: dispara; también puede disparar sin apuntar"),
                new ControlBinding("RIGHT CLICK", InputGesture.HOLD, ControlAction.FIRE_FIREARM,
                        "ARMAS DE FUEGO: mantiene la pulsación para 3A o AA"),
                new ControlBinding("R", InputGesture.PRESS, ControlAction.RELOAD_FIREARM,
                        "ARMAS DE FUEGO: sustituye el cartucho completo; durante una manipulación energética la cancela y vuelve al agarre normal"),
                new ControlBinding("R", InputGesture.HOLD, ControlAction.ENTER_PNEUMATIC_PRESSURIZATION,
                        "ARMAS NEUMÁTICAS: el personaje sujeta el mecanismo de presurización; RIGHT CLICK lo acciona"),
                new ControlBinding("R", InputGesture.HOLD, ControlAction.ENTER_ELECTROMAGNETIC_MANUAL_CHARGE,
                        "FUSIL BIFILAR: el personaje sujeta la manivela; RIGHT CLICK la hace girar y la carga admite avance continuo"),
                new ControlBinding("R", InputGesture.HOLD, ControlAction.ENTER_ARC_MANUAL_CHARGE,
                        "LANZA-ARCOS: la manivela es la acción manual preferente y avanza automáticamente mientras no se interrumpa; carga continua 1,2 / 2,1 / 3,0 s"),
                new ControlBinding("R", InputGesture.HOLD, ControlAction.ENTER_CLUSTER_TIMER_CONFIGURATION,
                        "CAÑÓN DE RACIMO: abre ajuste temporal; RIGHT CLICK alterna 3/4/5 s y R confirma/sale"),
                new ControlBinding("RIGHT CLICK", InputGesture.PRESS, ControlAction.LIGHT_ATTACK, "En tierra"),
                new ControlBinding("ALT IZQ", InputGesture.PRESS, ControlAction.HEAVY_ATTACK, "Ataque fuerte; la Maza Electro-mecánica resuelve aquí su descarga si está cargada"),
                new ControlBinding("ALT IZQ", InputGesture.HOLD, ControlAction.CHARGED_ATTACK, "Ataque cargado a dos manos; en el Fusil de Repetición se contextualiza como carga con bayoneta"),
                new ControlBinding("LEFT CLICK", InputGesture.PRESS, ControlAction.PARRY, "PARRY o inicio de bloqueo según el modo"),
                new ControlBinding("LEFT CLICK", InputGesture.HOLD, ControlAction.BLOCK, "Si el arma lo permite"),
                new ControlBinding("Z", InputGesture.PRESS, ControlAction.EXECUTE_ACTIVE_MASTERY, "Ejecuta la maestría activa seleccionada"),
                new ControlBinding("Z", InputGesture.HOLD, ControlAction.OPEN_ACTIVE_MASTERY_WHEEL, "Abre la rueda radial de maestrías activas"),
                new ControlBinding("X", InputGesture.PRESS, ControlAction.TOGGLE_SUSTAINED_MASTERY, "Activa o desactiva la maestría sostenida seleccionada según su política"),
                new ControlBinding("X", InputGesture.HOLD, ControlAction.OPEN_SUSTAINED_MASTERY_WHEEL, "Abre la rueda radial de maestrías sostenidas"),
                new ControlBinding("1", InputGesture.PRESS, ControlAction.QUICK_ACCESS_1, "Siempre disponible"),
                new ControlBinding("2", InputGesture.PRESS, ControlAction.QUICK_ACCESS_2, "Requiere polainas"),
                new ControlBinding("3", InputGesture.PRESS, ControlAction.QUICK_ACCESS_3, "Requiere pernera"),
                new ControlBinding("4", InputGesture.PRESS, ControlAction.QUICK_ACCESS_4, "Requiere bandolera"),
                new ControlBinding("I", InputGesture.PRESS, ControlAction.OPEN_INVENTORY, "Bloqueado durante un encuentro hostil"),
                new ControlBinding("H", InputGesture.PRESS, ControlAction.OPEN_CHARACTER_SHEET,
                        "Abre/cierra la Hoja del Personaje en tiempo real; permite inspección y subida de nivel"),
                new ControlBinding("P", InputGesture.PRESS, ControlAction.CYCLE_HUD_STATE, "Ocultar → Pausar → Reanudar y restaurar"),
                new ControlBinding("ESC", InputGesture.PRESS, ControlAction.OPEN_PAUSE_MENU, ""),
                new ControlBinding("F", InputGesture.PRESS, ControlAction.LOCK_OR_UNLOCK_TARGET, "Fijación a la altura del estómago; sin puntero visible"),
                new ControlBinding("M", InputGesture.PRESS, ControlAction.TOGGLE_WORLD_MEMORY,
                        "Abre/cierra la Memoria del Mundo con animación de recordar; bloqueado durante encuentros hostiles"),
                new ControlBinding("B", InputGesture.PRESS, ControlAction.CALL_PERSONAL_TRANSPORT,
                        "Silbido universal: si permanece dentro de 1.500 m, responde desde la posición donde fue dejado; solo fuera del renderizado puede materializarse entre 5 y 10 m cuando el nivel lo permita"),
                new ControlBinding("B", InputGesture.HOLD, ControlAction.OPEN_PERSONAL_TRANSPORT_WHEEL,
                        "Abre el menú circular de transportes adquiridos para cambiar el transporte seleccionado")
        );
    }
}
