package domain.inventory.item;

public enum AccessoryEffectType {
    HEALTH_REGENERATION_MULTIPLIER,
    SANITY_BONUS,
    INTERSTICE_SANITY_BONUS,
    NIGHT_SANITY_BONUS,
    ATTRIBUTE_BONUS,
    ALL_RESISTANCES_BONUS,
    HEALTH_REGEN_INHIBITION_IMMUNITY,
    VEIL_RIFT_NAVIGATION,
    ARTIFACT_ACTIVATION
}
