package domain.inventory.item;

public enum WeaponTrait {
    DE_ROTOR,
    DORSAL_ROTOR_COMPATIBLE,
    HELICOIDAL_CONTROL,
    SHIELD,
    UNARMED,
    ERGONOMIA_SUFICIENTE,
    ERGONOMIA_INTRINCADA,
    THERMO_MECHANICAL,
    ELECTRO_MECHANICAL_HEAVY,
    NON_DEGRADING,
    RESIN_REPAIR,
    HOOKS_WITH_BLUNT,
    STAFF_FLOURISH_HANDLING
}
