package domain.bestiarium.interstice.faerie;
import domain.ability.CharacterMasteryCollection; import domain.character.sheet.CharacterSheet; import domain.inventory.InventoryState; import domain.runic.*; import domain.save.GameSessionState; import java.util.*;
public final class Doppelganger {
 public static final String NARRATIVE_DESCRIPTION="No es una copia del individuo, sino la coexistencia de todas sus trayectorias cuando ninguna ha sido obligada todavía a subordinarse a una voluntad superior. Posee tu cuerpo porque todas fueron posibilidades de tu cuerpo. Posee tus objetos porque toda posibilidad parte de la misma historia material. Posee todas las maestrías porque ya las has hecho posibles. Y sostiene todas las Marcas simultáneamente porque todavía no necesita responder a la pregunta que tú sí debes responder: cuál de todas esas posibilidades eres. Cada agresión introduce una contradicción sobre la continuidad del yo —esto también eres tú—; por eso aquello que parece daño físico se resuelve como FRENESÍ: la herida visible sólo es la superficie de una agresión identitaria.";
 private final CharacterSheet sheet; private final InventoryState inventory; private final CharacterMasteryCollection masteries; private final Set<RunicMarkId> marks; private final double currentHealth,currentStamina;
 private Doppelganger(CharacterSheet sheet,InventoryState inventory,CharacterMasteryCollection masteries,double currentHealth,double currentStamina){this.sheet=sheet;this.inventory=inventory;this.masteries=masteries;this.marks=EnumSet.allOf(RunicMarkId.class);this.currentHealth=currentHealth;this.currentStamina=currentStamina;}
 public static Doppelganger mirrorOf(GameSessionState game){Objects.requireNonNull(game);return new Doppelganger(game.characterSheet(),game.currentInventory(),CharacterMasteryCollection.allCanonical(),game.vitalResources().currentHealth(),game.vitalResources().currentStamina());}
 public static Doppelganger mirrorOf(CharacterSheet sheet,InventoryState inventory){return new Doppelganger(Objects.requireNonNull(sheet),Objects.requireNonNull(inventory),CharacterMasteryCollection.allCanonical(),Double.NaN,Double.NaN);}
 public String narrativeDescription(){return NARRATIVE_DESCRIPTION;} public CharacterSheet sheet(){return sheet;} public InventoryState inventory(){return inventory;} public CharacterMasteryCollection masteries(){return masteries;} public Set<RunicMarkId> activeRunicMarks(){return Set.copyOf(marks);} public double currentHealth(){return currentHealth;} public double currentStamina(){return currentStamina;} public boolean runicMarkActive(RunicMarkId id, domain.ability.NullificationPolicy.SuppressionState suppression){return domain.runic.RunicMarkActivityPolicy.active(id,sheet,inventory.equipment(),marks,suppression);}
}
