package domain.bestiarium.physical_plane.ancient;

import java.util.List;

/** Documento de continuidad del ANCIENT INDÓMITO.  eleva su forma cambiada a una presencia antropomórfica majestuosa. */
public final class AnteoDoctrine {
    private AnteoDoctrine(){}
    public static String characterDescription(){return """
Anteo es el ANCIENT INDÓMITO y encarna la persistencia por contracción. Su CAMBIAFORMAS no reproduce un animal, una quimera ni una aberración zoológica: ese lenguaje corporal pertenece a ASPIRANT. La referencia visual de trabajo es la idea de una forma antropomórfica perfecta, depurada y de proporciones inequívocamente humanoides —comparable en concepto a la forma perfecta de Mahito en Jujutsu Kaisen—, pero reinterpretada por la biología y materiales propios de LIM hasta convertirse en una entidad soberana y no grotesca.

La silueta mantiene cabeza, tronco, dos brazos y dos piernas plenamente legibles. No necesita multiplicar miembros, raíces funcionales ni apéndices ambiguos para parecer sobrenatural. Su extrañeza procede de la perfección estructural, la escala de tensión que puede soportar y la manera en que cada línea anatómica parece haber sido refinada para transmitir fuerza sin pérdida. Incluso inmóvil debe evocar una majestuosidad inconmensurable: no parece un organismo que haya mutado para sobrevivir, sino una forma corporal que ha agotado posibilidades ordinarias y ha encontrado una solución superior.

La peculiaridad arbórea permanece en la piel, no en la anatomía. Toda la superficie corporal está compuesta por silicio pulido de apariencia mineral, organizado en vetas, placas y continuidades que recuerdan el crecimiento de un árbol antiguo. No es corteza rugosa. Es una piel lisa, dura y casi escultórica, con bifurcaciones y nervaduras discretas que sugieren tronco, duramen y crecimiento sin sacrificar la pureza antropomórfica. La luz resbala por ese silicio pulido y permite leer la estructura arbórea como profundidad material, no como ornamento adherido.

El endurecimiento funciona con la lógica cinética de Mortal Shell: Anteo puede rigidizar una región corporal en el instante preciso de una trayectoria, convirtiéndola temporalmente en una continuidad casi pétrea capaz de recibir o transmitir enormes impulsos. Sin embargo, su verdadera singularidad no es sólo endurecerse. Sus tendones y cadenas fasciales poseen una elasticidad extraordinaria. Puede precargar tensión mientras todavía se mueve, cambiar la rigidez de un apoyo y liberar esa energía en el siguiente paso, finta o golpe. Rigidez y elasticidad no son estados opuestos; son las dos fases de una misma máquina biomecánica.

Con ADAPTABILIDAD 119, Anteo lleva esa alternancia a un extremo que ningún humano puede reproducir. Al correr no necesita grandes gestos: comprime tendones durante el apoyo, endurece brevemente la estructura que recibe la reacción del suelo y libera la tensión hacia delante. Cada zancada arrastra una enorme inercia sin hacer que el movimiento parezca torpe. Al fintar puede cargar el cuerpo hacia una dirección, rigidizar el apoyo que habría confirmado esa trayectoria y liberar la tensión por la cadena contraria, produciendo cambios de vector súbitos pero físicamente continuos.

Sus golpes siguen el mismo principio. La velocidad inicial puede ser sorprendentemente ligera; la masa efectiva aparece al final, cuando el miembro se endurece y la cadena tendinosa entrega la tensión acumulada. El resultado no debe verse como una deformación grotesca ni como una extremidad convertida en arma. Es un puño, antebrazo, tibia, hombro o pie perfectamente reconocible que, durante una fracción de segundo, transmite la inercia de una estructura mucho más rígida de lo que su movimiento previo sugería.

La movilidad de Anteo debe transmitir dominio y economía. Puede correr con aceleraciones violentas, fintar con cambios de dirección extremadamente rápidos y encadenar golpes aprovechando la energía residual de la acción anterior. No se retuerce, no se arrastra y no se descompone visualmente. Sus desplazamientos son amplios cuando la inercia lo exige y mínimos cuando basta una transferencia de tensión. Cada movimiento conserva una lectura anatómica limpia, aunque su rapidez y capacidad para conservar momentum hagan difícil anticipar dónde terminará.

En forma humana Anteo conserva sus atributos, clase y maestrías. Al activar CAMBIAFORMAS mediante MOUSE WHEEL, la marca superpuesta sobrescribe la antigua marca PARHELIO, pero no cambia la ontología de sus impactos: Anteo sigue siendo una entidad física y sus golpes naturales son contundentes, con otros canales sólo cuando una superficie, arma o fenómeno material los justifique. Puede recibir perforante, cortante, contundente, veneno, quemadura, escarcha y electricidad según las resistencias ordinarias; MALDICIÓN y FRENESÍ no son canales corporales ANCIENT.

CARGADO es una propiedad bioeléctrica pasiva, no un ataque cargado ni una reserva ofensiva. Después de aplicar todos los filtros de resistencia, cualquier daño eléctrico neto rellena primero los PA que falten hasta PA TOTAL. Sólo la porción que exceda ese hueco energético continúa como daño eléctrico a PV. La electricidad absorbida no se conserva para un golpe posterior. Así, Anteo puede convertir una descarga recibida en recuperación de esfuerzo sin dejar de sufrir electricidad cuando ya no tiene PA que restaurar. La forma cambiada no rebaja su dignidad a monstruo: la eleva hasta una presencia ANCIENT cuyo diseño debe comunicar que el cuerpo antropomórfico puede resultar más inquietante y majestuoso cuando no necesita abandonar su propia perfección.
""";}

    public static List<String> attacks(){return List.of(
        "ATAQUES LIGEROS | Golpes antropomórficos limpios —puños, palmas, codos y patadas según ángulo— que aprovechan la elasticidad tendinosa para recuperar energía de una trayectoria y transferirla a la siguiente. El miembro endurece sólo en la ventana de impacto; el resto del movimiento conserva fluidez y una lectura marcial precisa.",
        "ATAQUES FUERTES | Anteo precarga una cadena tendinosa completa mediante cadera, tronco y apoyo, y libera un golpe único de gran recorrido. Justo antes del contacto endurece la cadena estructural necesaria para que la masa efectiva atraviese el objetivo sin convertir el gesto en una deformación corporal.",
        "ATAQUE CARGADO | Mantiene una postura antropomórfica contenida mientras acumula tensión elástica en piernas, cadera y torso. La descarga puede convertirse en un avance o golpe de enorme inercia. El valor visual está en la quietud previa y en la violencia limpia de la liberación, no en una transformación grotesca.",
        "ATAQUE CON SALTO | Comprime ambas cadenas inferiores, endurece el apoyo durante el impulso y libera la energía como una aceleración vertical u oblicua extraordinaria. En el aire conserva una silueta compacta y regia; el impacto descendente endurece el miembro ejecutor sólo al final para transferir la inercia acumulada.",
        "FINTAR | Precarga una trayectoria con hombros, cadera y apoyo como si fuese a comprometerse con ella; antes de cerrar el vector, endurece el punto de reacción y libera la tensión por la cadena contraria. El cambio de dirección es súbito, veloz y físicamente continuo, sin teletransporte ni dislocación visual.",
        "GOLPE DESESTABILIZADOR | Convierte suelo, piernas, pelvis y tronco en una única cadena de reacción durante un instante. La elasticidad acumula el impulso y el endurecimiento lo entrega al contacto, transmitiendo FUERZA + masa efectiva mediante una técnica marcial antropomórfica de máxima limpieza."
    );}
}
