package presentation.menu;
import application.save.GameSaveService; import domain.persona.*; import domain.save.*; import presentation.console.ConsoleInput; import presentation.loading.LoadingScreen; import java.io.PrintStream; import java.util.*;
public final class PersonaMenuScreen {
 public static final String ROLLBACK_WARNING="Lo perderás todo. Tu pasado, tu futuro, tu mismísima luz... Pero, si aceptas, con el tiempo te acabará dando igual ¿Estás seguro de que quieres volver a anhelar la verdadera fuerza a partir de este momento?";
 private final ConsoleInput input; private final PrintStream output; private final LoadingScreen loadingScreen; private final PersonaRegistry registry;
 public PersonaMenuScreen(ConsoleInput input,PrintStream output,LoadingScreen loadingScreen,PersonaRegistry registry){this.input=Objects.requireNonNull(input);this.output=Objects.requireNonNull(output);this.loadingScreen=Objects.requireNonNull(loadingScreen);this.registry=Objects.requireNonNull(registry);}
 public void open(PersonaProfile persona){if(!persona.gameCompleted()){loadingScreen.openFor(persona,persona.latestSave());return;}SaveSlot selected=selectSaveSlot(persona);if(selected==null)return;List<SaveSlot> ordered=persona.saveSlotsIn(SaveKind.WAKE);SaveSlot latestWake=ordered.isEmpty()?null:ordered.get(ordered.size()-1);if(selected.kind()==SaveKind.WAKE&&latestWake!=null&&!selected.id().equals(latestWake.id())){output.println("\\n"+ROLLBACK_WARNING);int confirm=input.readIntegerBetween("1. Aceptar  0. Cancelar: ",0,1);if(confirm==0)return;new GameSaveService(registry.saveRepository()).forgetAfterWake(persona.id(),selected);persona.forgetWakeSavesAfter(selected.metadata().createdAt());}registry.markLastSaved(persona);loadingScreen.openFor(persona,selected);}
 private SaveSlot selectSaveSlot(PersonaProfile persona){List<SaveSlot> visible=new ArrayList<>();output.println("\\nPARTIDAS GUARDADAS\\n");for(SaveKind kind:SaveKind.values()){output.println(kind.name());for(SaveSlot s:persona.saveSlotsIn(kind)){output.printf("%d. %s%n",visible.size()+1,s.title());visible.add(s);}if(persona.saveSlotsIn(kind).isEmpty())output.println("  — Sin recuerdos disponibles —");output.println();}output.println("0. Volver");int option=input.readIntegerBetween("Seleccione un punto de guardado: ",0,visible.size());return option==0?null:visible.get(option-1);}
}
