package presentation.menu;
import domain.persona.PersonaProfile; import domain.runic.*; import domain.inventory.equipment.EquipmentState; import presentation.console.ConsoleInput; import java.io.PrintStream; import java.util.*;
/** Opción de Hoja del Personaje habilitada tras [VOLUNTAD MAYOR]. */
public final class RunicMarkCollectionScreen {
 public static final String GENERAL_NARRATIVE="Una Marca Rúnica no concede una naturaleza. La registra. Mientras el individuo sólo ha completado las trayectorias que le son afines, la geometría puede manifestarse, pero todavía no existe prueba de que dicha organización sea estable frente a todas las configuraciones que el mismo individuo habría podido adoptar. Por ello, la primera Marca sólo se deja ver. Cuando las trayectorias restantes han alcanzado también su término y ninguna consigue desorganizar la primera, la figura deja de ser representación y adquiere función. Tras [VOLUNTAD MAYOR], ninguna Marca expresa ya aquello a lo que estabas condenado por afinidad: todas expresan posibilidades que has demostrado poder gobernar.";
 private final PersonaProfile persona; private final EquipmentState equipment; private final ConsoleInput input; private final PrintStream output;
 public RunicMarkCollectionScreen(PersonaProfile persona,EquipmentState equipment,ConsoleInput input,PrintStream output){this.persona=Objects.requireNonNull(persona);this.equipment=Objects.requireNonNull(equipment);this.input=Objects.requireNonNull(input);this.output=Objects.requireNonNull(output);equipment.synchronizeRunicSelection(persona);}
 public boolean available(){return persona.allRunicMarksUnlocked();}
 public void open(){if(!available())throw new IllegalStateException("Explorar Marcas Rúnicas todavía no está disponible.");output.println();output.println(GENERAL_NARRATIVE);output.println();var marks=RunicMarkCatalog.all();for(int i=0;i<marks.size();i++)output.println((i+1)+". "+marks.get(i).name());int selected=input.readIntegerBetween("MARCA> ",1,marks.size());persona.equipRunicMark(marks.get(selected-1).id());equipment.synchronizeRunicSelection(persona);output.println("Marca equipada: "+marks.get(selected-1).name()+".");}
}
