package domain.inventory.item.firearms;

public enum FirearmAction {
    TOGGLE_AIM,
    FIRE,
    RELOAD_CARTRIDGE,
    ENTER_PNEUMATIC_PRESSURIZATION,
    PRESSURIZE,
    CANCEL_PNEUMATIC_PRESSURIZATION,
    ENTER_ELECTROMAGNETIC_CHARGE_SELECTION,
    CYCLE_ELECTROMAGNETIC_CHARGE_SETTING,
    EXIT_ELECTROMAGNETIC_CHARGE_SELECTION,
    ENTER_ARC_MANUAL_CHARGE,
    TURN_ARC_CRANK,
    CANCEL_ARC_MANUAL_CHARGE,
    ENTER_CLUSTER_TIMER_CONFIGURATION,
    CYCLE_CLUSTER_TIMER,
    CANCEL_CLUSTER_TIMER_CONFIGURATION,
    CYCLE_FIRE_MODE,
    DESTABILIZE,
    BAYONET_THRUST,
    BAYONET_CHARGE,
    NONE
}
